/**
 * Adv module DB installation
 */

-- Default categories permssions
INSERT INTO `cot_auth` (`auth_groupid`, `auth_code`, `auth_option`,
  `auth_rights`, `auth_rights_lock`, `auth_setbyuserid`) VALUES
(1, 'vacancies', 'accountant', 1, 128, 1),
(2, 'vacancies', 'accountant', 1, 254, 1),
(3, 'vacancies', 'accountant', 0, 255, 1),
(4, 'vacancies', 'accountant', 3, 0, 0),
(5, 'vacancies', 'accountant', 255, 255, 1),
(6, 'vacancies', 'accountant', 3, 0, 0),
(1, 'vacancies', 'agro', 1, 128, 1),
(2, 'vacancies', 'agro', 1, 254, 1),
(3, 'vacancies', 'agro', 0, 255, 1),
(4, 'vacancies', 'agro', 3, 0, 0),
(5, 'vacancies', 'agro', 255, 255, 1),
(6, 'vacancies', 'agro', 3, 0, 0),
(1, 'vacancies', 'bank', 1, 128, 1),
(2, 'vacancies', 'bank', 1, 254, 1),
(3, 'vacancies', 'bank', 0, 255, 1),
(4, 'vacancies', 'bank', 3, 0, 0),
(5, 'vacancies', 'bank', 255, 255, 1),
(6, 'vacancies', 'bank', 3, 0, 0),
(1, 'vacancies', 'chief', 1, 128, 1),
(2, 'vacancies', 'chief', 1, 254, 1),
(3, 'vacancies', 'chief', 0, 255, 1),
(4, 'vacancies', 'chief', 3, 0, 0),
(5, 'vacancies', 'chief', 255, 255, 1),
(6, 'vacancies', 'chief', 3, 0, 0),
(1, 'vacancies', 'construction', 1, 128, 1),
(2, 'vacancies', 'construction', 1, 254, 1),
(3, 'vacancies', 'construction', 0, 255, 1),
(4, 'vacancies', 'construction', 3, 0, 0),
(5, 'vacancies', 'construction', 255, 255, 1),
(6, 'vacancies', 'construction', 3, 0, 0),
(1, 'vacancies', 'design-poligraph', 1, 128, 1),
(2, 'vacancies', 'design-poligraph', 1, 254, 1),
(3, 'vacancies', 'design-poligraph', 0, 255, 1),
(4, 'vacancies', 'design-poligraph', 3, 0, 0),
(5, 'vacancies', 'design-poligraph', 255, 255, 1),
(6, 'vacancies', 'design-poligraph', 3, 0, 0),
(1, 'vacancies', 'education', 1, 128, 1),
(2, 'vacancies', 'education', 1, 254, 1),
(3, 'vacancies', 'education', 0, 255, 1),
(4, 'vacancies', 'education', 3, 0, 0),
(5, 'vacancies', 'education', 255, 255, 1),
(6, 'vacancies', 'education', 3, 0, 0),
(1, 'vacancies', 'farma', 1, 128, 1),
(2, 'vacancies', 'farma', 1, 254, 1),
(3, 'vacancies', 'farma', 0, 255, 1),
(4, 'vacancies', 'farma', 3, 0, 0),
(5, 'vacancies', 'farma', 255, 255, 1),
(6, 'vacancies', 'farma', 3, 0, 0),
(1, 'vacancies', 'freelance', 1, 128, 1),
(2, 'vacancies', 'freelance', 1, 254, 1),
(3, 'vacancies', 'freelance', 0, 255, 1),
(4, 'vacancies', 'freelance', 3, 0, 0),
(5, 'vacancies', 'freelance', 255, 255, 1),
(6, 'vacancies', 'freelance', 3, 0, 0),
(1, 'vacancies', 'hr', 5, 0, 0),
(2, 'vacancies', 'hr', 1, 254, 1),
(3, 'vacancies', 'hr', 0, 255, 1),
(4, 'vacancies', 'hr', 7, 0, 0),
(5, 'vacancies', 'hr', 255, 255, 1),
(6, 'vacancies', 'hr', 135, 0, 0),
(1, 'vacancies', 'insurance', 1, 128, 1),
(2, 'vacancies', 'insurance', 1, 254, 1),
(3, 'vacancies', 'insurance', 0, 255, 1),
(4, 'vacancies', 'insurance', 3, 0, 0),
(5, 'vacancies', 'insurance', 255, 255, 1),
(6, 'vacancies', 'insurance', 3, 0, 0),
(1, 'vacancies', 'IT', 1, 128, 1),
(2, 'vacancies', 'IT', 1, 254, 1),
(3, 'vacancies', 'IT', 0, 255, 1),
(4, 'vacancies', 'IT', 3, 0, 0),
(5, 'vacancies', 'IT', 255, 255, 1),
(6, 'vacancies', 'IT', 3, 0, 0),
(1, 'vacancies', 'job-students', 1, 128, 1),
(2, 'vacancies', 'job-students', 1, 254, 1),
(3, 'vacancies', 'job-students', 0, 255, 1),
(4, 'vacancies', 'job-students', 3, 0, 0),
(5, 'vacancies', 'job-students', 255, 255, 1),
(6, 'vacancies', 'job-students', 3, 0, 0),
(1, 'vacancies', 'lawyer', 1, 128, 1),
(2, 'vacancies', 'lawyer', 1, 254, 1),
(3, 'vacancies', 'lawyer', 0, 255, 1),
(4, 'vacancies', 'lawyer', 3, 0, 0),
(5, 'vacancies', 'lawyer', 255, 255, 1),
(6, 'vacancies', 'lawyer', 3, 0, 0),
(1, 'vacancies', 'logistics', 1, 128, 1),
(2, 'vacancies', 'logistics', 1, 254, 1),
(3, 'vacancies', 'logistics', 0, 255, 1),
(4, 'vacancies', 'logistics', 3, 0, 0),
(5, 'vacancies', 'logistics', 255, 255, 1),
(6, 'vacancies', 'logistics', 3, 0, 0),
(1, 'vacancies', 'manufacturing', 1, 128, 1),
(2, 'vacancies', 'manufacturing', 1, 254, 1),
(3, 'vacancies', 'manufacturing', 0, 255, 1),
(4, 'vacancies', 'manufacturing', 3, 0, 0),
(5, 'vacancies', 'manufacturing', 255, 255, 1),
(6, 'vacancies', 'manufacturing', 3, 0, 0),
(1, 'vacancies', 'marketing-pr', 1, 128, 1),
(2, 'vacancies', 'marketing-pr', 1, 254, 1),
(3, 'vacancies', 'marketing-pr', 0, 255, 1),
(4, 'vacancies', 'marketing-pr', 3, 0, 0),
(5, 'vacancies', 'marketing-pr', 255, 255, 1),
(6, 'vacancies', 'marketing-pr', 3, 0, 0),
(1, 'vacancies', 'medicine', 1, 128, 1),
(2, 'vacancies', 'medicine', 1, 254, 1),
(3, 'vacancies', 'medicine', 0, 255, 1),
(4, 'vacancies', 'medicine', 3, 0, 0),
(5, 'vacancies', 'medicine', 255, 255, 1),
(6, 'vacancies', 'medicine', 3, 0, 0),
(1, 'vacancies', 'mlm', 1, 128, 1),
(2, 'vacancies', 'mlm', 1, 254, 1),
(3, 'vacancies', 'mlm', 0, 255, 1),
(4, 'vacancies', 'mlm', 3, 0, 0),
(5, 'vacancies', 'mlm', 255, 255, 1),
(6, 'vacancies', 'mlm', 3, 0, 0),
(1, 'vacancies', 'other', 1, 128, 1),
(2, 'vacancies', 'other', 1, 254, 1),
(3, 'vacancies', 'other', 0, 255, 1),
(4, 'vacancies', 'other', 3, 0, 0),
(5, 'vacancies', 'other', 255, 255, 1),
(6, 'vacancies', 'other', 3, 0, 0),
(1, 'vacancies', 'procurement', 1, 128, 1),
(2, 'vacancies', 'procurement', 1, 254, 1),
(3, 'vacancies', 'procurement', 0, 255, 1),
(4, 'vacancies', 'procurement', 3, 0, 0),
(5, 'vacancies', 'procurement', 255, 255, 1),
(6, 'vacancies', 'procurement', 3, 0, 0),
(1, 'vacancies', 'publishing', 1, 128, 1),
(2, 'vacancies', 'publishing', 1, 254, 1),
(3, 'vacancies', 'publishing', 0, 255, 1),
(4, 'vacancies', 'publishing', 3, 0, 0),
(5, 'vacancies', 'publishing', 255, 255, 1),
(6, 'vacancies', 'publishing', 3, 0, 0),
(1, 'vacancies', 'radio-tv', 1, 128, 1),
(2, 'vacancies', 'radio-tv', 1, 254, 1),
(3, 'vacancies', 'radio-tv', 0, 255, 1),
(4, 'vacancies', 'radio-tv', 3, 0, 0),
(5, 'vacancies', 'radio-tv', 255, 255, 1),
(6, 'vacancies', 'radio-tv', 3, 0, 0),
(1, 'vacancies', 'real-estate', 1, 128, 1),
(2, 'vacancies', 'real-estate', 1, 254, 1),
(3, 'vacancies', 'real-estate', 0, 255, 1),
(4, 'vacancies', 'real-estate', 3, 0, 0),
(5, 'vacancies', 'real-estate', 255, 255, 1),
(6, 'vacancies', 'real-estate', 3, 0, 0),
(1, 'vacancies', 'restaurant', 1, 128, 1),
(2, 'vacancies', 'restaurant', 1, 254, 1),
(3, 'vacancies', 'restaurant', 0, 255, 1),
(4, 'vacancies', 'restaurant', 3, 0, 0),
(5, 'vacancies', 'restaurant', 255, 255, 1),
(6, 'vacancies', 'restaurant', 3, 0, 0),
(1, 'vacancies', 'sales', 1, 128, 1),
(2, 'vacancies', 'sales', 1, 254, 1),
(3, 'vacancies', 'sales', 0, 255, 1),
(4, 'vacancies', 'sales', 3, 0, 0),
(5, 'vacancies', 'sales', 255, 255, 1),
(6, 'vacancies', 'sales', 3, 0, 0),
(1, 'vacancies', 'secretary', 1, 128, 1),
(2, 'vacancies', 'secretary', 1, 254, 1),
(3, 'vacancies', 'secretary', 0, 255, 1),
(4, 'vacancies', 'secretary', 3, 0, 0),
(5, 'vacancies', 'secretary', 255, 255, 1),
(6, 'vacancies', 'secretary', 3, 0, 0),
(1, 'vacancies', 'security', 1, 128, 1),
(2, 'vacancies', 'security', 1, 254, 1),
(3, 'vacancies', 'security', 0, 255, 1),
(4, 'vacancies', 'security', 3, 0, 0),
(5, 'vacancies', 'security', 255, 255, 1),
(6, 'vacancies', 'security', 3, 0, 0),
(1, 'vacancies', 'service-industry', 1, 128, 1),
(2, 'vacancies', 'service-industry', 1, 254, 1),
(3, 'vacancies', 'service-industry', 0, 255, 1),
(4, 'vacancies', 'service-industry', 3, 0, 0),
(5, 'vacancies', 'service-industry', 255, 255, 1),
(6, 'vacancies', 'service-industry', 3, 0, 0),
(1, 'vacancies', 'show', 1, 128, 1),
(2, 'vacancies', 'show', 1, 254, 1),
(3, 'vacancies', 'show', 0, 255, 1),
(4, 'vacancies', 'show', 3, 0, 0),
(5, 'vacancies', 'show', 255, 255, 1),
(6, 'vacancies', 'show', 3, 0, 0),
(1, 'vacancies', 'travel-tourism', 1, 128, 1),
(2, 'vacancies', 'travel-tourism', 1, 254, 1),
(3, 'vacancies', 'travel-tourism', 0, 255, 1),
(4, 'vacancies', 'travel-tourism', 3, 0, 0),
(5, 'vacancies', 'travel-tourism', 255, 255, 1),
(6, 'vacancies', 'travel-tourism', 3, 0, 0),
(1, 'vacancies', 'vehicles-car', 1, 128, 1),
(2, 'vacancies', 'vehicles-car', 1, 254, 1),
(3, 'vacancies', 'vehicles-car', 0, 255, 1),
(4, 'vacancies', 'vehicles-car', 3, 0, 0),
(5, 'vacancies', 'vehicles-car', 255, 255, 1),
(6, 'vacancies', 'vehicles-car', 3, 0, 1);

-- Vacancies table
CREATE TABLE IF NOT EXISTS `cot_vacancies` (
  `vac_id` int(11) unsigned NOT NULL auto_increment,
  `vac_alias` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `vac_state` tinyint(1) unsigned NOT NULL default '0',
  `vac_cat` varchar(255) collate utf8_unicode_ci NOT NULL,
  `vac_title` varchar(255) collate utf8_unicode_ci NOT NULL,
  `vac_desc` MEDIUMTEXT collate utf8_unicode_ci default NULL,
  `vac_keywords` varchar(255) collate utf8_unicode_ci default NULL,
  `vac_metatitle` varchar(255) collate utf8_unicode_ci default NULL,
  `vac_metadesc` varchar(255) collate utf8_unicode_ci default NULL,
  `vac_ownerid` int(11) NOT NULL default '0',
  `vac_date` int(11) NOT NULL default '0',
  `vac_updated` int(11) NOT NULL default '0',
  `vac_count` mediumint(8) unsigned default '0',
  `vac_rating` decimal(5,2) NOT NULL default '0.00',
  `vac_duty` MEDIUMTEXT collate utf8_unicode_ci NOT NULL,
  `vac_term` MEDIUMTEXT collate utf8_unicode_ci NOT NULL,
  `vac_age` varchar(255) collate utf8_unicode_ci default NULL,
  `vac_sex` char(1) collate utf8_unicode_ci NOT NULL default 'U',
  `vac_edu` varchar(255) collate utf8_unicode_ci default NULL,
  `vac_exp` varchar(255) collate utf8_unicode_ci default NULL,
  `vac_qua` MEDIUMTEXT collate utf8_unicode_ci NOT NULL,
  `vac_empl` varchar(50) collate utf8_unicode_ci default NULL,
  `vac_schedule` varchar(50) collate utf8_unicode_ci default NULL,
  `vac_salary` varchar(255) collate utf8_unicode_ci default NULL,
  `vac_addr` varchar(255) collate utf8_unicode_ci default NULL,
  `vac_phone` varchar(255) collate utf8_unicode_ci default NULL,
  `vac_skype` varchar(50) collate utf8_unicode_ci default NULL,
  `vac_site` varchar(255) collate utf8_unicode_ci default NULL,
  `vac_email` varchar(50) collate utf8_unicode_ci default NULL,
  `vac_expire` int(11) NOT NULL default '0',
  `vac_hidemail` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`vac_id`),
  KEY `vac_cat` (`vac_cat`),
  KEY `vac_alias` (`vac_alias`),
  KEY `vac_state` (`vac_state`),
  KEY `vac_date` (`vac_date`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Default vacancies categories
INSERT INTO `cot_structure` (`structure_area`, `structure_code`, `structure_path`, `structure_tpl`, `structure_title`, `structure_seotitle`,
   `structure_desc`, `structure_text`, `structure_icon`, `structure_locked`, `structure_count`) VALUES
('vacancies', 'IT', '2', '', 'IT', 'IT', '', '', '', 0, 0),
('vacancies', 'agro', '3', '', 'Агропромышленный комплекс', '', '', '', '', 0, 0),
('vacancies', 'bank', '4', '', 'Банки - Финансы - Лизинг', '', '', '', '', 0, 0),
('vacancies', 'accountant', '5', '', 'Бухгалтерия - Аудит - Финансы предприятия', '', '', '', '', 0, 0),
('vacancies', 'restaurant', '6', '', 'Гостиницы - Рестораны - Кафе', '', '', '', '', 0, 0),
('vacancies', 'design-poligraph', '7', '', 'Дизайнерское дело', '', '', '', '', 0, 0),
('vacancies', 'procurement', '8', '', 'Закупки и снабжение', '', '', '', '', 0, 0),
('vacancies', 'show', '9', '', 'Культура - Мода - Развлечения - Спорт', '', '', '', '', 0, 0),
('vacancies', 'logistics', '10', '', 'Логистика - Таможня - Склад', '', '', '', '', 0, 0),
('vacancies', 'marketing-pr', '11', '', 'Маркетинг - Реклама - PR', '', '', '', '', 0, 0),
('vacancies', 'publishing', '12', '', 'Медиа - Издательское дело', '', '', '', '', 0, 0),
('vacancies', 'medicine', '13', '', 'Медицина - Здравоохранение', '', '', '', '', 0, 0),
('vacancies', 'education', '14', '', 'Наука - Образование - Перевод', '', '', '', '', 0, 0),
('vacancies', 'real-estate', '15', '', 'Недвижимость', '', '', '', '', 0, 0),
('vacancies', 'security', '16', '', 'Охрана и безопасность', '', '', '', '', 0, 0),
('vacancies', 'manufacturing', '17', '', 'Промышленность - Производство', '', '', '', '', 0, 0),
('vacancies', 'secretary', '18', '', 'Секретариат - Офис - АХО', '', '', '', '', 0, 0),
('vacancies', 'mlm', '19', '', 'Сетевой маркетинг - MLM', '', '', '', '', 0, 0),
('vacancies', 'insurance', '20', '', 'Страхование', '', '', '', '', 0, 0),
('vacancies', 'construction', '21', '', 'Строительство и Архитектура', '', '', '', '', 0, 0),
('vacancies', 'service-industry', '22', '', 'Сфера обслуживания', '', '', '', '', 0, 0),
('vacancies', 'radio-tv', '23', '', 'Телекоммуникации и связь', '', '', '', '', 0, 0),
('vacancies', 'chief', '24', '', 'ТОП-Менеджмент', '', '', '', '', 0, 0),
('vacancies', 'sales', '25', '', 'Торговля и Продажи', '', '', '', '', 0, 0),
('vacancies', 'vehicles-car', '26', '', 'Транспорт - Авто - Сервисное обслуживание', '', '', '', '', 0, 0),
('vacancies', 'travel-tourism', '27', '', 'Туризм и Путешествия', '', '', '', '', 0, 0),
('vacancies', 'farma', '28', '', 'Фармация', '', '', '', '', 0, 0),
('vacancies', 'lawyer', '29', '', 'Юриспруденция', '', '', '', '', 0, 0),
('vacancies', 'job-students', '30', '', 'Работа для студентов', '', '', '', '', 0, 0),
('vacancies', 'freelance', '31', '', 'Фриланс и Удаленная работа', '', '', '', '', 0, 0),
('vacancies', 'other', '32', '', 'Другие виды заработка', '', '', '', '', 0, 0),
('vacancies', 'hr', '1', '', 'HR специалисты, Бизнес-тренеры', '', '', '', '', 0, 0);
