/**
 * board module DB installation
 */

-- Default categories permssions
INSERT INTO `cot_auth` (`auth_groupid`, `auth_code`, `auth_option`,
  `auth_rights`, `auth_rights_lock`, `auth_setbyuserid`) VALUES

(1, 'board', 'stroitelnye-materialy', 1, 128, 1),
(2, 'board', 'stroitelnye-materialy', 1, 254, 1),
(3, 'board', 'stroitelnye-materialy', 0, 255, 1),
(4, 'board', 'stroitelnye-materialy', 3, 0, 0),
(5, 'board', 'stroitelnye-materialy', 255, 255, 1),
(6, 'board', 'stroitelnye-materialy', 3, 0, 0),
(1, 'board', 'alyuminievye-profili', 1, 128, 1),
(2, 'board', 'alyuminievye-profili', 1, 254, 1),
(3, 'board', 'alyuminievye-profili', 0, 255, 1),
(4, 'board', 'alyuminievye-profili', 3, 0, 0),
(5, 'board', 'alyuminievye-profili', 255, 255, 1),
(6, 'board', 'alyuminievye-profili', 3, 0, 0),
(1, 'board', 'armatura', 1, 128, 1),
(2, 'board', 'armatura', 1, 254, 1),
(3, 'board', 'armatura', 0, 255, 1),
(4, 'board', 'armatura', 3, 0, 0),
(5, 'board', 'armatura', 255, 255, 1),
(6, 'board', 'armatura', 3, 0, 0),
(1, 'board', 'balka-balka-metallicheskaya', 1, 128, 1),
(2, 'board', 'balka-balka-metallicheskaya', 1, 254, 1),
(3, 'board', 'balka-balka-metallicheskaya', 0, 255, 1),
(4, 'board', 'balka-balka-metallicheskaya', 3, 0, 0),
(5, 'board', 'balka-balka-metallicheskaya', 255, 255, 1),
(6, 'board', 'balka-balka-metallicheskaya', 3, 0, 0),
(1, 'board', 'kanaty-tsepi-tros', 1, 128, 1),
(2, 'board', 'kanaty-tsepi-tros', 1, 254, 1),
(3, 'board', 'kanaty-tsepi-tros', 0, 255, 1),
(4, 'board', 'kanaty-tsepi-tros', 3, 0, 0),
(5, 'board', 'kanaty-tsepi-tros', 255, 255, 1),
(6, 'board', 'kanaty-tsepi-tros', 3, 0, 0),
(1, 'board', 'katanka-provoloka', 1, 128, 1),
(2, 'board', 'katanka-provoloka', 1, 254, 1),
(3, 'board', 'katanka-provoloka', 0, 255, 1),
(4, 'board', 'katanka-provoloka', 3, 0, 0),
(5, 'board', 'katanka-provoloka', 255, 255, 1),
(6, 'board', 'katanka-provoloka', 3, 0, 0),
(1, 'board', 'kvadrat', 1, 128, 1),
(2, 'board', 'kvadrat', 1, 254, 1),
(3, 'board', 'kvadrat', 0, 255, 1),
(4, 'board', 'kvadrat', 3, 0, 0),
(5, 'board', 'kvadrat', 255, 255, 1),
(6, 'board', 'kvadrat', 3, 0, 0),
(1, 'board', 'krug', 1, 128, 1),
(2, 'board', 'krug', 1, 254, 1),
(3, 'board', 'krug', 0, 255, 1),
(4, 'board', 'krug', 3, 0, 0),
(5, 'board', 'krug', 255, 255, 1),
(6, 'board', 'krug', 3, 0, 0),
(1, 'board', 'list-listovoy-prokat', 1, 128, 1),
(2, 'board', 'list-listovoy-prokat', 1, 254, 1),
(3, 'board', 'list-listovoy-prokat', 0, 255, 1),
(4, 'board', 'list-listovoy-prokat', 3, 0, 0),
(5, 'board', 'list-listovoy-prokat', 255, 255, 1),
(6, 'board', 'list-listovoy-prokat', 3, 0, 0),
(1, 'board', 'polosa', 1, 128, 1),
(2, 'board', 'polosa', 1, 254, 1),
(3, 'board', 'polosa', 0, 255, 1),
(4, 'board', 'polosa', 3, 0, 0),
(5, 'board', 'polosa', 255, 255, 1),
(6, 'board', 'polosa', 3, 0, 0),
(1, 'board', 'profil-lstk', 1, 128, 1),
(2, 'board', 'profil-lstk', 1, 254, 1),
(3, 'board', 'profil-lstk', 0, 255, 1),
(4, 'board', 'profil-lstk', 3, 0, 0),
(5, 'board', 'profil-lstk', 255, 255, 1),
(6, 'board', 'profil-lstk', 3, 0, 0),
(1, 'board', 'profilnye-truby', 1, 128, 1),
(2, 'board', 'profilnye-truby', 1, 254, 1),
(3, 'board', 'profilnye-truby', 0, 255, 1),
(4, 'board', 'profilnye-truby', 3, 0, 0),
(5, 'board', 'pprofilnye-truby', 255, 255, 1),
(6, 'board', 'profilnye-truby', 3, 0, 0),
(1, 'board', 'setka-metallicheskaya', 1, 128, 1),
(2, 'board', 'setka-metallicheskaya', 1, 254, 1),
(3, 'board', 'setka-metallicheskaya', 0, 255, 1),
(4, 'board', 'setka-metallicheskaya', 3, 0, 0),
(5, 'board', 'setka-metallicheskaya', 255, 255, 1),
(6, 'board', 'setka-metallicheskaya', 3, 0, 0),
(1, 'board', 'ugolok', 1, 128, 1),
(2, 'board', 'ugolok', 1, 254, 1),
(3, 'board', 'ugolok', 0, 255, 1),
(4, 'board', 'ugolok', 3, 0, 0),
(5, 'board', 'ugolok', 255, 255, 1),
(6, 'board', 'ugolok', 3, 0, 0),
(1, 'board', 'shveller', 1, 128, 1),
(2, 'board', 'shveller', 1, 254, 1),
(3, 'board', 'shveller', 0, 255, 1),
(4, 'board', 'shveller', 3, 0, 0),
(5, 'board', 'shveller', 255, 255, 1),
(6, 'board', 'shveller', 3, 0, 0),
(1, 'board', 'shestigrannik', 1, 128, 1),
(2, 'board', 'shestigrannik', 1, 254, 1),
(3, 'board', 'shestigrannik', 0, 255, 1),
(4, 'board', 'shestigrannik', 3, 0, 0),
(5, 'board', 'shestigrannik', 255, 255, 1),
(6, 'board', 'shestigrannik', 3, 0, 0),
(1, 'board', 'shtrips-shtrips-otsinkovannyy', 1, 128, 1),
(2, 'board', 'shtrips-shtrips-otsinkovannyy', 1, 254, 1),
(3, 'board', 'shtrips-shtrips-otsinkovannyy', 0, 255, 1),
(4, 'board', 'shtrips-shtrips-otsinkovannyy', 3, 0, 0),
(5, 'board', 'shtrips-shtrips-otsinkovannyy', 255, 255, 1),
(6, 'board', 'shtrips-shtrips-otsinkovannyy', 3, 0, 0),
(1, 'board', 'krovelnye-materialy', 1, 128, 1),
(2, 'board', 'krovelnye-materialy', 1, 254, 1),
(3, 'board', 'krovelnye-materialy', 0, 255, 1),
(4, 'board', 'krovelnye-materialy', 3, 0, 0),
(5, 'board', 'krovelnye-materialy', 255, 255, 1),
(6, 'board', 'krovelnye-materialy', 3, 0, 0),
(1, 'board', 'antiobledenenie', 1, 128, 1),
(2, 'board', 'antiobledenenie', 1, 254, 1),
(3, 'board', 'antiobledenenie', 0, 255, 1),
(4, 'board', 'antiobledenenie', 3, 0, 0),
(5, 'board', 'antiobledenenie', 255, 255, 1),
(6, 'board', 'antiobledenenie', 3, 0, 0),
(1, 'board', 'bitumnaya-cherepitsa', 1, 128, 1),
(2, 'board', 'bitumnaya-cherepitsa', 1, 254, 1),
(3, 'board', 'bitumnaya-cherepitsa', 0, 255, 1),
(4, 'board', 'bitumnaya-cherepitsa', 3, 0, 0),
(5, 'board', 'bitumnaya-cherepitsa', 255, 255, 1),
(6, 'board', 'bitumnaya-cherepitsa', 3, 0, 0),
(1, 'board', 'ventilyatsionnye-i-prokhodnye-elementy', 1, 128, 1),
(2, 'board', 'ventilyatsionnye-i-prokhodnye-elementy', 1, 254, 1),
(3, 'board', 'ventilyatsionnye-i-prokhodnye-elementy', 0, 255, 1),
(4, 'board', 'ventilyatsionnye-i-prokhodnye-elementy', 3, 0, 0),
(5, 'board', 'ventilyatsionnye-i-prokhodnye-elementy', 255, 255, 1),
(6, 'board', 'ventilyatsionnye-i-prokhodnye-elementy', 3, 0, 0),
(1, 'board', 'keramoplast', 1, 128, 1),
(2, 'board', 'keramoplast', 1, 254, 1),
(3, 'board', 'keramoplast', 0, 255, 1),
(4, 'board', 'keramoplast', 3, 0, 0),
(5, 'board', 'keramoplast', 255, 255, 1),
(6, 'board', 'keramoplast', 3, 0, 0),
(1, 'board', 'kompozitnaya-metallocherepitsa', 1, 128, 1),
(2, 'board', 'kompozitnaya-metallocherepitsa', 1, 254, 1),
(3, 'board', 'kompozitnaya-metallocherepitsa', 0, 255, 1),
(4, 'board', 'kompozitnaya-metallocherepitsa', 3, 0, 0),
(5, 'board', 'kompozitnaya-metallocherepitsa', 255, 255, 1),
(6, 'board', 'kompozitnaya-metallocherepitsa', 3, 0, 0),
(1, 'board', 'krovelnye-lenty', 1, 128, 1),
(2, 'board', 'krovelnye-lenty', 1, 254, 1),
(3, 'board', 'krovelnye-lenty', 0, 255, 1),
(4, 'board', 'krovelnye-lenty', 3, 0, 0),
(5, 'board', 'krovelnye-lenty', 255, 255, 1),
(6, 'board', 'krovelnye-lenty', 3, 0, 0),
(1, 'board', 'krovelnyy-krepezh', 1, 128, 1),
(2, 'board', 'krovelnyy-krepezh', 1, 254, 1),
(3, 'board', 'krovelnyy-krepezh', 0, 255, 1),
(4, 'board', 'krovelnyy-krepezh', 3, 0, 0),
(5, 'board', 'krovelnyy-krepezh', 255, 255, 1),
(6, 'board', 'krovelnyy-krepezh', 3, 0, 0),
(1, 'board', 'metallocherepitsa', 1, 128, 1),
(2, 'board', 'metallocherepitsa', 1, 254, 1),
(3, 'board', 'metallocherepitsa', 0, 255, 1),
(4, 'board', 'metallocherepitsa', 3, 0, 0),
(5, 'board', 'metallocherepitsa', 255, 255, 1),
(6, 'board', 'metallocherepitsa', 3, 0, 0),
(1, 'board', 'podkrovelnye-plenki-i-membrany', 1, 128, 1),
(2, 'board', 'podkrovelnye-plenki-i-membrany', 1, 254, 1),
(3, 'board', 'podkrovelnye-plenki-i-membrany', 0, 255, 1),
(4, 'board', 'podkrovelnye-plenki-i-membrany', 3, 0, 0),
(5, 'board', 'podkrovelnye-plenki-i-membrany', 255, 255, 1),
(6, 'board', 'podkrovelnye-plenki-i-membrany', 3, 0, 0),
(1, 'board', 'polikarbonat-orgsteklo', 1, 128, 1),
(2, 'board', 'polikarbonat-orgsteklo', 1, 254, 1),
(3, 'board', 'polikarbonat-orgsteklo', 0, 255, 1),
(4, 'board', 'polikarbonat-orgsteklo', 3, 0, 0),
(5, 'board', 'polikarbonat-orgsteklo', 255, 255, 1),
(6, 'board', 'polikarbonat-orgsteklo', 3, 0, 0),
(1, 'board', 'profnastil', 1, 128, 1),
(2, 'board', 'profnastil', 1, 254, 1),
(3, 'board', 'profnastil', 0, 255, 1),
(4, 'board', 'profnastil', 3, 0, 0),
(5, 'board', 'profnastil', 255, 255, 1),
(6, 'board', 'profnastil', 3, 0, 0),
(1, 'board', 'sistemy-snegozaderzhaniya-lestnitsy', 1, 128, 1),
(2, 'board', 'sistemy-snegozaderzhaniya-lestnitsy', 1, 254, 1),
(3, 'board', 'sistemy-snegozaderzhaniya-lestnitsy', 0, 255, 1),
(4, 'board', 'sistemy-snegozaderzhaniya-lestnitsy', 3, 0, 0),
(5, 'board', 'sistemy-snegozaderzhaniya-lestnitsy', 255, 255, 1),
(6, 'board', 'sistemy-snegozaderzhaniya-lestnitsy', 3, 0, 0),
(1, 'board', 'zenitnye-fonari-steklyannye-kryshi', 1, 128, 1),
(2, 'board', 'zenitnye-fonari-steklyannye-kryshi', 1, 254, 1),
(3, 'board', 'zenitnye-fonari-steklyannye-kryshi', 0, 255, 1),
(4, 'board', 'zenitnye-fonari-steklyannye-kryshi', 3, 0, 0),
(5, 'board', 'zenitnye-fonari-steklyannye-kryshi', 255, 255, 1),
(6, 'board', 'zenitnye-fonari-steklyannye-kryshi', 3, 0, 0),
(1, 'board', 'faltsevaya-krovlya', 1, 128, 1),
(2, 'board', 'faltsevaya-krovlya', 1, 254, 1),
(3, 'board', 'faltsevaya-krovlya', 0, 255, 1),
(4, 'board', 'faltsevaya-krovlya', 3, 0, 0),
(5, 'board', 'faltsevaya-krovlya', 255, 255, 1),
(6, 'board', 'faltsevaya-krovlya', 3, 0, 0),
(1, 'board', 'faltsevaya-krovlya', 1, 128, 1),
(2, 'board', 'faltsevaya-krovlya', 1, 254, 1),
(3, 'board', 'faltsevaya-krovlya', 0, 255, 1),
(4, 'board', 'faltsevaya-krovlya', 3, 0, 0),
(5, 'board', 'faltsevaya-krovlya', 255, 255, 1),
(6, 'board', 'faltsevaya-krovlya', 3, 0, 0),
(1, 'board', 'cherepitsa', 1, 128, 1),
(2, 'board', 'cherepitsa', 1, 254, 1),
(3, 'board', 'cherepitsa', 0, 255, 1),
(4, 'board', 'cherepitsa', 3, 0, 0),
(5, 'board', 'cherepitsa', 255, 255, 1),
(6, 'board', 'cherepitsa', 3, 0, 0),
(1, 'board', 'cherepitsa', 1, 128, 1),
(2, 'board', 'cherepitsa', 1, 254, 1),
(3, 'board', 'cherepitsa', 0, 255, 1),
(4, 'board', 'cherepitsa', 3, 0, 0),
(5, 'board', 'cherepitsa', 255, 255, 1),
(6, 'board', 'cherepitsa', 3, 0, 0),
(1, 'board', 'shifer-evroshifer', 1, 128, 1),
(2, 'board', 'shifer-evroshifer', 1, 254, 1),
(3, 'board', 'shifer-evroshifer', 0, 255, 1),
(4, 'board', 'shifer-evroshifer', 3, 0, 0),
(5, 'board', 'shifer-evroshifer', 255, 255, 1),
(6, 'board', 'shifer-evroshifer', 3, 0, 0),
(1, 'board', 'beton-zhbi', 1, 128, 1),
(2, 'board', 'beton-zhbi', 1, 254, 1),
(3, 'board', 'beton-zhbi', 0, 255, 1),
(4, 'board', 'beton-zhbi', 3, 0, 0),
(5, 'board', 'beton-zhbi', 255, 255, 1),
(6, 'board', 'beton-zhbi', 3, 0, 0),
(1, 'board', 'balki-progony-rigelya', 1, 128, 1),
(2, 'board', 'balki-progony-rigelya', 1, 254, 1),
(3, 'board', 'balki-progony-rigelya', 0, 255, 1),
(4, 'board', 'balki-progony-rigelya', 3, 0, 0),
(5, 'board', 'balki-progony-rigelya', 255, 255, 1),
(6, 'board', 'balki-progony-rigelya', 3, 0, 0),
(1, 'board', 'balki-progony-rigelya', 1, 128, 1),
(2, 'board', 'balki-progony-rigelya', 1, 254, 1),
(3, 'board', 'balki-progony-rigelya', 0, 255, 1),
(4, 'board', 'balki-progony-rigelya', 3, 0, 0),
(5, 'board', 'balki-progony-rigelya', 255, 255, 1),
(6, 'board', 'balki-progony-rigelya', 3, 0, 0),
(1, 'board', 'beton', 1, 128, 1),
(2, 'board', 'beton', 1, 254, 1),
(3, 'board', 'beton', 0, 255, 1),
(4, 'board', 'beton', 3, 0, 0),
(5, 'board', 'beton', 255, 255, 1),
(6, 'board', 'beton', 3, 0, 0),
(1, 'board', 'ventilyatsionnye-bloki', 1, 128, 1),
(2, 'board', 'ventilyatsionnye-bloki', 1, 254, 1),
(3, 'board', 'ventilyatsionnye-bloki', 0, 255, 1),
(4, 'board', 'ventilyatsionnye-bloki', 3, 0, 0),
(5, 'board', 'ventilyatsionnye-bloki', 255, 255, 1),
(6, 'board', 'ventilyatsionnye-bloki', 3, 0, 0),
(1, 'board', 'dobavki-v-beton-plastifikatory-pigmenty', 1, 128, 1),
(2, 'board', 'dobavki-v-beton-plastifikatory-pigmenty', 1, 254, 1),
(3, 'board', 'dobavki-v-beton-plastifikatory-pigmenty', 0, 255, 1),
(4, 'board', 'dobavki-v-beton-plastifikatory-pigmenty', 3, 0, 0),
(5, 'board', 'dobavki-v-beton-plastifikatory-pigmenty', 255, 255, 1),
(6, 'board', 'dobavki-v-beton-plastifikatory-pigmenty', 3, 0, 0),
(1, 'board', 'dorozhnye-plity', 1, 128, 1),
(2, 'board', 'dorozhnye-plity', 1, 254, 1),
(3, 'board', 'dorozhnye-plity', 0, 255, 1),
(4, 'board', 'dorozhnye-plity', 3, 0, 0),
(5, 'board', 'dorozhnye-plity', 255, 255, 1),
(6, 'board', 'dorozhnye-plity', 3, 0, 0),
(1, 'board', 'zhelezobetonnyy-zabor-evrozabor', 1, 128, 1),
(2, 'board', 'zhelezobetonnyy-zabor-evrozabor', 1, 254, 1),
(3, 'board', 'zhelezobetonnyy-zabor-evrozabor', 0, 255, 1),
(4, 'board', 'zhelezobetonnyy-zabor-evrozabor', 3, 0, 0),
(5, 'board', 'zhelezobetonnyy-zabor-evrozabor', 255, 255, 1),
(6, 'board', 'zhelezobetonnyy-zabor-evrozabor', 3, 0, 0),
(1, 'board', 'inzhenernye-seti', 1, 128, 1),
(2, 'board', 'inzhenernye-seti', 1, 254, 1),
(3, 'board', 'inzhenernye-seti', 0, 255, 1),
(4, 'board', 'inzhenernye-seti', 3, 0, 0),
(5, 'board', 'inzhenernye-seti', 255, 255, 1),
(6, 'board', 'inzhenernye-seti', 3, 0, 0),
(1, 'board', 'koltsa-kryshki-dno-dlya-kolodtsa', 1, 128, 1),
(2, 'board', 'koltsa-kryshki-dno-dlya-kolodtsa', 1, 254, 1),
(3, 'board', 'koltsa-kryshki-dno-dlya-kolodtsa', 0, 255, 1),
(4, 'board', 'koltsa-kryshki-dno-dlya-kolodtsa', 3, 0, 0),
(5, 'board', 'koltsa-kryshki-dno-dlya-kolodtsa', 255, 255, 1),
(6, 'board', 'koltsa-kryshki-dno-dlya-kolodtsa', 3, 0, 0),
(1, 'board', 'lestnichnye-marshi-i-stupeni', 1, 128, 1),
(2, 'board', 'lestnichnye-marshi-i-stupeni', 1, 254, 1),
(3, 'board', 'lestnichnye-marshi-i-stupeni', 0, 255, 1),
(4, 'board', 'lestnichnye-marshi-i-stupeni', 3, 0, 0),
(5, 'board', 'lestnichnye-marshi-i-stupeni', 255, 255, 1),
(6, 'board', 'lestnichnye-marshi-i-stupeni', 3, 0, 0),
(1, 'board', 'lestnichnye-ploshchadki', 1, 128, 1),
(2, 'board', 'lestnichnye-ploshchadki', 1, 254, 1),
(3, 'board', 'lestnichnye-ploshchadki', 0, 255, 1),
(4, 'board', 'lestnichnye-ploshchadki', 3, 0, 0),
(5, 'board', 'lestnichnye-ploshchadki', 255, 255, 1),
(6, 'board', 'lestnichnye-ploshchadki', 3, 0, 0),
(1, 'board', 'liftovye-shakhty', 1, 128, 1),
(2, 'board', 'liftovye-shakhty', 1, 254, 1),
(3, 'board', 'liftovye-shakhty', 0, 255, 1),
(4, 'board', 'liftovye-shakhty', 3, 0, 0),
(5, 'board', 'liftovye-shakhty', 255, 255, 1),
(6, 'board', 'liftovye-shakhty', 3, 0, 0),
(1, 'board', 'lotki-plity-perekrytiya-lotkov', 1, 128, 1),
(2, 'board', 'lotki-plity-perekrytiya-lotkov', 1, 254, 1),
(3, 'board', 'lotki-plity-perekrytiya-lotkov', 0, 255, 1),
(4, 'board', 'lotki-plity-perekrytiya-lotkov', 3, 0, 0),
(5, 'board', 'lotki-plity-perekrytiya-lotkov', 255, 255, 1),
(6, 'board', 'lotki-plity-perekrytiya-lotkov', 3, 0, 0),
(1, 'board', 'paneli-i-plity-perekrytiya', 1, 128, 1),
(2, 'board', 'paneli-i-plity-perekrytiya', 1, 254, 1),
(3, 'board', 'paneli-i-plity-perekrytiya', 0, 255, 1),
(4, 'board', 'paneli-i-plity-perekrytiya', 3, 0, 0),
(5, 'board', 'paneli-i-plity-perekrytiya', 255, 255, 1),
(6, 'board', 'paneli-i-plity-perekrytiya', 3, 0, 0),
(1, 'board', 'peremychki', 1, 128, 1),
(2, 'board', 'peremychki', 1, 254, 1),
(3, 'board', 'peremychki', 0, 255, 1),
(4, 'board', 'peremychki', 3, 0, 0),
(5, 'board', 'peremychki', 255, 255, 1),
(6, 'board', 'peremychki', 3, 0, 0),
(1, 'board', 'plity-balkonov-i-lodzhiy', 1, 128, 1),
(2, 'board', 'plity-balkonov-i-lodzhiy', 1, 254, 1),
(3, 'board', 'plity-balkonov-i-lodzhiy', 0, 255, 1),
(4, 'board', 'plity-balkonov-i-lodzhiy', 3, 0, 0),
(5, 'board', 'plity-balkonov-i-lodzhiy', 255, 255, 1),
(6, 'board', 'plity-balkonov-i-lodzhiy', 3, 0, 0),
(1, 'board', 'sbornye-zhelezobetonnye-garazhi', 1, 128, 1),
(2, 'board', 'sbornye-zhelezobetonnye-garazhi', 1, 254, 1),
(3, 'board', 'sbornye-zhelezobetonnye-garazhi', 0, 255, 1),
(4, 'board', 'sbornye-zhelezobetonnye-garazhi', 3, 0, 0),
(5, 'board', 'sbornye-zhelezobetonnye-garazhi', 255, 255, 1),
(6, 'board', 'sbornye-zhelezobetonnye-garazhi', 3, 0, 0),
(1, 'board', 'svai-opory-lep-stolby', 1, 128, 1),
(2, 'board', 'svai-opory-lep-stolby', 1, 254, 1),
(3, 'board', 'svai-opory-lep-stolby', 0, 255, 1),
(4, 'board', 'svai-opory-lep-stolby', 3, 0, 0),
(5, 'board', 'svai-opory-lep-stolby', 255, 255, 1),
(6, 'board', 'svai-opory-lep-stolby', 3, 0, 0),
(1, 'board', 'truby-zhelezobetonnye', 1, 128, 1),
(2, 'board', 'truby-zhelezobetonnye', 1, 254, 1),
(3, 'board', 'truby-zhelezobetonnye', 0, 255, 1),
(4, 'board', 'truby-zhelezobetonnye', 3, 0, 0),
(5, 'board', 'truby-zhelezobetonnye', 255, 255, 1),
(6, 'board', 'truby-zhelezobetonnye', 3, 0, 0),
(1, 'board', 'fibra-fibrovolokno', 1, 128, 1),
(2, 'board', 'fibra-fibrovolokno', 1, 254, 1),
(3, 'board', 'fibra-fibrovolokno', 0, 255, 1),
(4, 'board', 'fibra-fibrovolokno', 3, 0, 0),
(5, 'board', 'fibra-fibrovolokno', 255, 255, 1),
(6, 'board', 'fibra-fibrovolokno', 3, 0, 0),
(1, 'board', 'fundamentnye-bloki-fundamenty', 1, 128, 1),
(2, 'board', 'fundamentnye-bloki-fundamenty', 1, 254, 1),
(3, 'board', 'fundamentnye-bloki-fundamenty', 0, 255, 1),
(4, 'board', 'fundamentnye-bloki-fundamenty', 3, 0, 0),
(5, 'board', 'fundamentnye-bloki-fundamenty', 255, 255, 1),
(6, 'board', 'fundamentnye-bloki-fundamenty', 3, 0, 0),
(1, 'board', 'pilomaterialy', 1, 128, 1),
(2, 'board', 'pilomaterialy', 1, 254, 1),
(3, 'board', 'pilomaterialy', 0, 255, 1),
(4, 'board', 'pilomaterialy', 3, 0, 0),
(5, 'board', 'pilomaterialy', 255, 255, 1),
(6, 'board', 'pilomaterialy', 3, 0, 0),
(1, 'board', 'bambuk-rattan-pressforming', 1, 128, 1),
(2, 'board', 'bambuk-rattan-pressforming', 1, 254, 1),
(3, 'board', 'bambuk-rattan-pressforming', 0, 255, 1),
(4, 'board', 'bambuk-rattan-pressforming', 3, 0, 0),
(5, 'board', 'bambuk-rattan-pressforming', 255, 255, 1),
(6, 'board', 'bambuk-rattan-pressforming', 3, 0, 0),
(1, 'board', 'blok-khaus', 1, 128, 1),
(2, 'board', 'blok-khaus', 1, 254, 1),
(3, 'board', 'blok-khaus', 0, 255, 1),
(4, 'board', 'blok-khaus', 3, 0, 0),
(5, 'board', 'blok-khaus', 255, 255, 1),
(6, 'board', 'blok-khaus', 3, 0, 0),
(1, 'board', 'brus', 1, 128, 1),
(2, 'board', 'brus', 1, 254, 1),
(3, 'board', 'brus', 0, 255, 1),
(4, 'board', 'brus', 3, 0, 0),
(5, 'board', 'brus', 255, 255, 1),
(6, 'board', 'brus', 3, 0, 0),
(1, 'board', 'brusok-i-reyka-montazhnaya', 1, 128, 1),
(2, 'board', 'brusok-i-reyka-montazhnaya', 1, 254, 1),
(3, 'board', 'brusok-i-reyka-montazhnaya', 0, 255, 1),
(4, 'board', 'brusok-i-reyka-montazhnaya', 3, 0, 0),
(5, 'board', 'brusok-i-reyka-montazhnaya', 255, 255, 1),
(6, 'board', 'brusok-i-reyka-montazhnaya', 3, 0, 0),
(1, 'board', 'dvp', 1, 128, 1),
(2, 'board', 'dvp', 1, 254, 1),
(3, 'board', 'dvp', 0, 255, 1),
(4, 'board', 'dvp', 3, 0, 0),
(5, 'board', 'dvp', 255, 255, 1),
(6, 'board', 'dvp', 3, 0, 0),
(1, 'board', 'derevyannaya-vagonka', 1, 128, 1),
(2, 'board', 'derevyannaya-vagonka', 1, 254, 1),
(3, 'board', 'derevyannaya-vagonka', 0, 255, 1),
(4, 'board', 'derevyannaya-vagonka', 3, 0, 0),
(5, 'board', 'derevyannaya-vagonka', 255, 255, 1),
(6, 'board', 'derevyannaya-vagonka', 3, 0, 0),
(1, 'board', 'doska-zabornaya', 1, 128, 1),
(2, 'board', 'doska-zabornaya', 1, 254, 1),
(3, 'board', 'doska-zabornaya', 0, 255, 1),
(4, 'board', 'doska-zabornaya', 3, 0, 0),
(5, 'board', 'doska-zabornaya', 255, 255, 1),
(6, 'board', 'doska-zabornaya', 3, 0, 0),
(1, 'board', 'doska-neobreznaya-obapoly', 1, 128, 1),
(2, 'board', 'doska-neobreznaya-obapoly', 1, 254, 1),
(3, 'board', 'doska-neobreznaya-obapoly', 0, 255, 1),
(4, 'board', 'doska-neobreznaya-obapoly', 3, 0, 0),
(5, 'board', 'doska-neobreznaya-obapoly', 255, 255, 1),
(6, 'board', 'doska-neobreznaya-obapoly', 3, 0, 0),
(1, 'board', 'doska-obreznaya', 1, 128, 1),
(2, 'board', 'doska-obreznaya', 1, 254, 1),
(3, 'board', 'doska-obreznaya', 0, 255, 1),
(4, 'board', 'doska-obreznaya', 3, 0, 0),
(5, 'board', 'doska-obreznaya', 255, 255, 1),
(6, 'board', 'doska-obreznaya', 3, 0, 0),
(1, 'board', 'drova-kolotye-drova', 1, 128, 1),
(2, 'board', 'drova-kolotye-drova', 1, 254, 1),
(3, 'board', 'drova-kolotye-drova', 0, 255, 1),
(4, 'board', 'drova-kolotye-drova', 3, 0, 0),
(5, 'board', 'drova-kolotye-drova', 255, 255, 1),
(6, 'board', 'drova-kolotye-drova', 3, 0, 0),
(1, 'board', 'dsp', 1, 128, 1),
(2, 'board', 'dsp', 1, 254, 1),
(3, 'board', 'dsp', 0, 255, 1),
(4, 'board', 'dsp', 3, 0, 0),
(5, 'board', 'dsp', 255, 255, 1),
(6, 'board', 'dsp', 3, 0, 0),
(1, 'board', 'kleenyy-brus-i-profilirovannyy-brus', 1, 128, 1),
(2, 'board', 'kleenyy-brus-i-profilirovannyy-brus', 1, 254, 1),
(3, 'board', 'kleenyy-brus-i-profilirovannyy-brus', 0, 255, 1),
(4, 'board', 'kleenyy-brus-i-profilirovannyy-brus', 3, 0, 0),
(5, 'board', 'kleenyy-brus-i-profilirovannyy-brus', 255, 255, 1),
(6, 'board', 'kleenyy-brus-i-profilirovannyy-brus', 3, 0, 0),
(1, 'board', 'kruglye-lesomaterialy', 1, 128, 1),
(2, 'board', 'kruglye-lesomaterialy', 1, 254, 1),
(3, 'board', 'kruglye-lesomaterialy', 0, 255, 1),
(4, 'board', 'kruglye-lesomaterialy', 3, 0, 0),
(5, 'board', 'kruglye-lesomaterialy', 255, 255, 1),
(6, 'board', 'kruglye-lesomaterialy', 3, 0, 0),
(1, 'board', 'mdf', 1, 128, 1),
(2, 'board', 'mdf', 1, 254, 1),
(3, 'board', 'mdf', 0, 255, 1),
(4, 'board', 'mdf', 3, 0, 0),
(5, 'board', 'mdf', 255, 255, 1),
(6, 'board', 'mdf', 3, 0, 0),
(1, 'board', 'mebelnye-shchity', 1, 128, 1),
(2, 'board', 'mebelnye-shchity', 1, 254, 1),
(3, 'board', 'mebelnye-shchity', 0, 255, 1),
(4, 'board', 'mebelnye-shchity', 3, 0, 0),
(5, 'board', 'mebelnye-shchity', 255, 255, 1),
(6, 'board', 'mebelnye-shchity', 3, 0, 0),
(1, 'board', 'nalichniki', 1, 128, 1),
(2, 'board', 'nalichniki', 1, 254, 1),
(3, 'board', 'nalichniki', 0, 255, 1),
(4, 'board', 'nalichniki', 3, 0, 0),
(5, 'board', 'nalichniki', 255, 255, 1),
(6, 'board', 'nalichniki', 3, 0, 0),
(1, 'board', 'orientirovanno-struzhechnye-plity', 1, 128, 1),
(2, 'board', 'orientirovanno-struzhechnye-plity', 1, 254, 1),
(3, 'board', 'orientirovanno-struzhechnye-plity', 0, 255, 1),
(4, 'board', 'orientirovanno-struzhechnye-plity', 3, 0, 0),
(5, 'board', 'orientirovanno-struzhechnye-plity', 255, 255, 1),
(6, 'board', 'orientirovanno-struzhechnye-plity', 3, 0, 0),
(1, 'board', 'plintus', 1, 128, 1),
(2, 'board', 'plintus', 1, 254, 1),
(3, 'board', 'plintus', 0, 255, 1),
(4, 'board', 'plintus', 3, 0, 0),
(5, 'board', 'plintus', 255, 255, 1),
(6, 'board', 'plintus', 3, 0, 0),
(1, 'board', 'pogonazh', 1, 128, 1),
(2, 'board', 'pogonazh', 1, 254, 1),
(3, 'board', 'pogonazh', 0, 255, 1),
(4, 'board', 'pogonazh', 3, 0, 0),
(5, 'board', 'pogonazh', 255, 255, 1),
(6, 'board', 'pogonazh', 3, 0, 0),
(1, 'board', 'falsh-brus', 1, 128, 1),
(2, 'board', 'falsh-brus', 1, 254, 1),
(3, 'board', 'falsh-brus', 0, 255, 1),
(4, 'board', 'falsh-brus', 3, 0, 0),
(5, 'board', 'falsh-brus', 255, 255, 1),
(6, 'board', 'falsh-brus', 3, 0, 0),
(1, 'board', 'fanera', 1, 128, 1),
(2, 'board', 'fanera', 1, 254, 1),
(3, 'board', 'fanera', 0, 255, 1),
(4, 'board', 'fanera', 3, 0, 0),
(5, 'board', 'fanera', 255, 255, 1),
(6, 'board', 'fanera', 3, 0, 0),
(1, 'board', 'shpon-mebelnyy-shpon', 1, 128, 1),
(2, 'board', 'shpon-mebelnyy-shpon', 1, 254, 1),
(3, 'board', 'shpon-mebelnyy-shpon', 0, 255, 1),
(4, 'board', 'shpon-mebelnyy-shpon', 3, 0, 0),
(5, 'board', 'shpon-mebelnyy-shpon', 255, 255, 1),
(6, 'board', 'shpon-mebelnyy-shpon', 3, 0, 0),
(1, 'board', 'kladochnye-materialy', 1, 128, 1),
(2, 'board', 'kladochnye-materialy', 1, 254, 1),
(3, 'board', 'kladochnye-materialy', 0, 255, 1),
(4, 'board', 'kladochnye-materialy', 3, 0, 0),
(5, 'board', 'kladochnye-materialy', 255, 255, 1),
(6, 'board', 'kladochnye-materialy', 3, 0, 0),
(1, 'board', 'butovyy-kamen', 1, 128, 1),
(2, 'board', 'butovyy-kamen', 1, 254, 1),
(3, 'board', 'butovyy-kamen', 0, 255, 1),
(4, 'board', 'butovyy-kamen', 3, 0, 0),
(5, 'board', 'butovyy-kamen', 255, 255, 1),
(6, 'board', 'butovyy-kamen', 3, 0, 0),
(1, 'board', 'butovyy-kamen', 1, 128, 1),
(2, 'board', 'butovyy-kamen', 1, 254, 1),
(3, 'board', 'butovyy-kamen', 0, 255, 1),
(4, 'board', 'butovyy-kamen', 3, 0, 0),
(5, 'board', 'butovyy-kamen', 255, 255, 1),
(6, 'board', 'butovyy-kamen', 3, 0, 0),
(1, 'board', 'gazobloki-gazobeton', 1, 128, 1),
(2, 'board', 'gazobloki-gazobeton', 1, 254, 1),
(3, 'board', 'gazobloki-gazobeton', 0, 255, 1),
(4, 'board', 'gazobloki-gazobeton', 3, 0, 0),
(5, 'board', 'gazobloki-gazobeton', 255, 255, 1),
(6, 'board', 'gazobloki-gazobeton', 3, 0, 0),
(1, 'board', 'kamen-rakushnyak-rakushechnik', 1, 128, 1),
(2, 'board', 'kamen-rakushnyak-rakushechnik', 1, 254, 1),
(3, 'board', 'kamen-rakushnyak-rakushechnik', 0, 255, 1),
(4, 'board', 'kamen-rakushnyak-rakushechnik', 3, 0, 0),
(5, 'board', 'kamen-rakushnyak-rakushechnik', 255, 255, 1),
(6, 'board', 'kamen-rakushnyak-rakushechnik', 3, 0, 0),
(1, 'board', 'keramzitobetonnye-bloki', 1, 128, 1),
(2, 'board', 'keramzitobetonnye-bloki', 1, 254, 1),
(3, 'board', 'keramzitobetonnye-bloki', 0, 255, 1),
(4, 'board', 'keramzitobetonnye-bloki', 3, 0, 0),
(5, 'board', 'keramzitobetonnye-bloki', 255, 255, 1),
(6, 'board', 'keramzitobetonnye-bloki', 3, 0, 0),
(1, 'board', 'keramicheskie-bloki', 1, 128, 1),
(2, 'board', 'keramicheskie-bloki', 1, 254, 1),
(3, 'board', 'keramicheskie-bloki', 0, 255, 1),
(4, 'board', 'keramicheskie-bloki', 3, 0, 0),
(5, 'board', 'keramicheskie-bloki', 255, 255, 1),
(6, 'board', 'keramicheskie-bloki', 3, 0, 0),
(1, 'board', 'kirpich-klinkernyy', 1, 128, 1),
(2, 'board', 'kirpich-klinkernyy', 1, 254, 1),
(3, 'board', 'kirpich-klinkernyy', 0, 255, 1),
(4, 'board', 'kirpich-klinkernyy', 3, 0, 0),
(5, 'board', 'kirpich-klinkernyy', 255, 255, 1),
(6, 'board', 'kirpich-klinkernyy', 3, 0, 0),
(1, 'board', 'kirpich-klinkernyy-ruchnoy-formovki', 1, 128, 1),
(2, 'board', 'kirpich-klinkernyy-ruchnoy-formovki', 1, 254, 1),
(3, 'board', 'kirpich-klinkernyy-ruchnoy-formovki', 0, 255, 1),
(4, 'board', 'kirpich-klinkernyy-ruchnoy-formovki', 3, 0, 0),
(5, 'board', 'kirpich-klinkernyy-ruchnoy-formovki', 255, 255, 1),
(6, 'board', 'kirpich-klinkernyy-ruchnoy-formovki', 3, 0, 0),
(1, 'board', 'kirpich-ogneupornyy', 1, 128, 1),
(2, 'board', 'kirpich-ogneupornyy', 1, 254, 1),
(3, 'board', 'kirpich-ogneupornyy', 0, 255, 1),
(4, 'board', 'kirpich-ogneupornyy', 3, 0, 0),
(5, 'board', 'kirpich-ogneupornyy', 255, 255, 1),
(6, 'board', 'kirpich-ogneupornyy', 3, 0, 0),
(1, 'board', 'kirpich-ryadovoy', 1, 128, 1),
(2, 'board', 'kirpich-ryadovoy', 1, 254, 1),
(3, 'board', 'kirpich-ryadovoy', 0, 255, 1),
(4, 'board', 'kirpich-ryadovoy', 3, 0, 0),
(5, 'board', 'kirpich-ryadovoy', 255, 255, 1),
(6, 'board', 'kirpich-ryadovoy', 3, 0, 0),
(1, 'board', 'kirpich-silikatnyy', 1, 128, 1),
(2, 'board', 'kirpich-silikatnyy', 1, 254, 1),
(3, 'board', 'kirpich-silikatnyy', 0, 255, 1),
(4, 'board', 'kirpich-silikatnyy', 3, 0, 0),
(5, 'board', 'kirpich-silikatnyy', 255, 255, 1),
(6, 'board', 'kirpich-silikatnyy', 3, 0, 0),
(1, 'board', 'oblitsovochnyy-kirpich', 1, 128, 1),
(2, 'board', 'oblitsovochnyy-kirpich', 1, 254, 1),
(3, 'board', 'oblitsovochnyy-kirpich', 0, 255, 1),
(4, 'board', 'oblitsovochnyy-kirpich', 3, 0, 0),
(5, 'board', 'oblitsovochnyy-kirpich', 255, 255, 1),
(6, 'board', 'oblitsovochnyy-kirpich', 3, 0, 0),
(1, 'board', 'parapet-kryshki-na-zabor', 1, 128, 1),
(2, 'board', 'parapet-kryshki-na-zabor', 1, 254, 1),
(3, 'board', 'parapet-kryshki-na-zabor', 0, 255, 1),
(4, 'board', 'parapet-kryshki-na-zabor', 3, 0, 0),
(5, 'board', 'parapet-kryshki-na-zabor', 255, 255, 1),
(6, 'board', 'parapet-kryshki-na-zabor', 3, 0, 0),
(1, 'board', 'penobloki-penobeton', 1, 128, 1),
(2, 'board', 'penobloki-penobeton', 1, 254, 1),
(3, 'board', 'penobloki-penobeton', 0, 255, 1),
(4, 'board', 'penobloki-penobeton', 3, 0, 0),
(5, 'board', 'penobloki-penobeton', 255, 255, 1),
(6, 'board', 'penobloki-penobeton', 3, 0, 0),
(1, 'board', 'stenovye-bloki', 1, 128, 1),
(2, 'board', 'stenovye-bloki', 1, 254, 1),
(3, 'board', 'stenovye-bloki', 0, 255, 1),
(4, 'board', 'stenovye-bloki', 3, 0, 0),
(5, 'board', 'stenovye-bloki', 255, 255, 1),
(6, 'board', 'stenovye-bloki', 3, 0, 0),
(1, 'board', 'termobloki', 1, 128, 1),
(2, 'board', 'termobloki', 1, 254, 1),
(3, 'board', 'termobloki', 0, 255, 1),
(4, 'board', 'termobloki', 3, 0, 0),
(5, 'board', 'termobloki', 255, 255, 1),
(6, 'board', 'termobloki', 3, 0, 0),
(1, 'board', 'shlakobloki', 1, 128, 1),
(2, 'board', 'shlakobloki', 1, 254, 1),
(3, 'board', 'shlakobloki', 0, 255, 1),
(4, 'board', 'shlakobloki', 3, 0, 0),
(5, 'board', 'shlakobloki', 255, 255, 1),
(6, 'board', 'shlakobloki', 3, 0, 0),
(1, 'board', 'fasadnye-materialy', 1, 128, 1),
(2, 'board', 'fasadnye-materialy', 1, 254, 1),
(3, 'board', 'fasadnye-materialy', 0, 255, 1),
(4, 'board', 'fasadnye-materialy', 3, 0, 0),
(5, 'board', 'fasadnye-materialy', 255, 255, 1),
(6, 'board', 'fasadnye-materialy', 3, 0, 0),
(1, 'board', 'ventiliruemye-fasady', 1, 128, 1),
(2, 'board', 'ventiliruemye-fasady', 1, 254, 1),
(3, 'board', 'ventiliruemye-fasady', 0, 255, 1),
(4, 'board', 'ventiliruemye-fasady', 3, 0, 0),
(5, 'board', 'ventiliruemye-fasady', 255, 255, 1),
(6, 'board', 'ventiliruemye-fasady', 3, 0, 0),
(1, 'board', 'dekor-dlya-fasadov', 1, 128, 1),
(2, 'board', 'dekor-dlya-fasadov', 1, 254, 1),
(3, 'board', 'dekor-dlya-fasadov', 0, 255, 1),
(4, 'board', 'dekor-dlya-fasadov', 3, 0, 0),
(5, 'board', 'dekor-dlya-fasadov', 255, 255, 1),
(6, 'board', 'dekor-dlya-fasadov', 3, 0, 0),
(1, 'board', 'dyubelya-fasadnye', 1, 128, 1),
(2, 'board', 'dyubelya-fasadnye', 1, 254, 1),
(3, 'board', 'dyubelya-fasadnye', 0, 255, 1),
(4, 'board', 'dyubelya-fasadnye', 3, 0, 0),
(5, 'board', 'dyubelya-fasadnye', 255, 255, 1),
(6, 'board', 'dyubelya-fasadnye', 3, 0, 0),
(1, 'board', 'klinkernaya-plitka', 1, 128, 1),
(2, 'board', 'klinkernaya-plitka', 1, 254, 1),
(3, 'board', 'klinkernaya-plitka', 0, 255, 1),
(4, 'board', 'klinkernaya-plitka', 3, 0, 0),
(5, 'board', 'klinkernaya-plitka', 255, 255, 1),
(6, 'board', 'klinkernaya-plitka', 3, 0, 0),
(1, 'board', 'metallicheskie-paneli', 1, 128, 1),
(2, 'board', 'metallicheskie-paneli', 1, 254, 1),
(3, 'board', 'metallicheskie-paneli', 0, 255, 1),
(4, 'board', 'metallicheskie-paneli', 3, 0, 0),
(5, 'board', 'metallicheskie-paneli', 255, 255, 1),
(6, 'board', 'metallicheskie-paneli', 3, 0, 0),
(1, 'board', 'oblitsovochnye-termopaneli', 1, 128, 1),
(2, 'board', 'oblitsovochnye-termopaneli', 1, 254, 1),
(3, 'board', 'oblitsovochnye-termopaneli', 0, 255, 1),
(4, 'board', 'oblitsovochnye-termopaneli', 3, 0, 0),
(5, 'board', 'oblitsovochnye-termopaneli', 255, 255, 1),
(6, 'board', 'oblitsovochnye-termopaneli', 3, 0, 0),
(1, 'board', 'ochistka-fasadov', 1, 128, 1),
(2, 'board', 'ochistka-fasadov', 1, 254, 1),
(3, 'board', 'ochistka-fasadov', 0, 255, 1),
(4, 'board', 'ochistka-fasadov', 3, 0, 0),
(5, 'board', 'ochistka-fasadov', 255, 255, 1),
(6, 'board', 'ochistka-fasadov', 3, 0, 0),
(1, 'board', 'sayding', 1, 128, 1),
(2, 'board', 'sayding', 1, 254, 1),
(3, 'board', 'sayding', 0, 255, 1),
(4, 'board', 'sayding', 3, 0, 0),
(5, 'board', 'sayding', 255, 255, 1),
(6, 'board', 'sayding', 3, 0, 0),
(1, 'board', 'sistemy-utepleniya-fasadov', 1, 128, 1),
(2, 'board', 'sistemy-utepleniya-fasadov', 1, 254, 1),
(3, 'board', 'sistemy-utepleniya-fasadov', 0, 255, 1),
(4, 'board', 'sistemy-utepleniya-fasadov', 3, 0, 0),
(5, 'board', 'sistemy-utepleniya-fasadov', 255, 255, 1),
(6, 'board', 'sistemy-utepleniya-fasadov', 3, 0, 0),
(1, 'board', 'sofity', 1, 128, 1),
(2, 'board', 'sofity', 1, 254, 1),
(3, 'board', 'sofity', 0, 255, 1),
(4, 'board', 'sofity', 3, 0, 0),
(5, 'board', 'sofity', 255, 255, 1),
(6, 'board', 'sofity', 3, 0, 0),
(1, 'board', 'steklyannye-fasady', 1, 128, 1),
(2, 'board', 'steklyannye-fasady', 1, 254, 1),
(3, 'board', 'steklyannye-fasady', 0, 255, 1),
(4, 'board', 'steklyannye-fasady', 3, 0, 0),
(5, 'board', 'steklyannye-fasady', 255, 255, 1),
(6, 'board', 'steklyannye-fasady', 3, 0, 0),
(1, 'board', 'sendvich-paneli-sip-paneli', 1, 128, 1),
(2, 'board', 'sendvich-paneli-sip-paneli', 1, 254, 1),
(3, 'board', 'sendvich-paneli-sip-paneli', 0, 255, 1),
(4, 'board', 'sendvich-paneli-sip-paneli', 3, 0, 0),
(5, 'board', 'sendvich-paneli-sip-paneli', 255, 255, 1),
(6, 'board', 'sendvich-paneli-sip-paneli', 3, 0, 0),
(1, 'board', 'fasadnaya-plitka', 1, 128, 1),
(2, 'board', 'fasadnaya-plitkai', 1, 254, 1),
(3, 'board', 'fasadnaya-plitka', 0, 255, 1),
(4, 'board', 'fasadnaya-plitka', 3, 0, 0),
(5, 'board', 'fasadnaya-plitka', 255, 255, 1),
(6, 'board', 'fasadnaya-plitka', 3, 0, 0),
(1, 'board', 'fasadnye-paneli', 1, 128, 1),
(2, 'board', 'fasadnye-paneli', 1, 254, 1),
(3, 'board', 'fasadnye-paneli', 0, 255, 1),
(4, 'board', 'fasadnye-paneli', 3, 0, 0),
(5, 'board', 'fasadnye-paneli', 255, 255, 1),
(6, 'board', 'fasadnye-paneli', 3, 0, 0),
(1, 'board', 'fasadnyy-kamen', 1, 128, 1),
(2, 'board', 'fasadnyy-kamen', 1, 254, 1),
(3, 'board', 'fasadnyy-kamen', 0, 255, 1),
(4, 'board', 'fasadnyy-kamen', 3, 0, 0),
(5, 'board', 'fasadnyy-kamen', 255, 255, 1),
(6, 'board', 'fasadnyy-kamen', 3, 0, 0),
(1, 'board', 'fasadnyy-krepezh', 1, 128, 1),
(2, 'board', 'fasadnyy-krepezh', 1, 254, 1),
(3, 'board', 'fasadnyy-krepezh', 0, 255, 1),
(4, 'board', 'fasadnyy-krepezh', 3, 0, 0),
(5, 'board', 'fasadnyy-krepezh', 255, 255, 1),
(6, 'board', 'fasadnyy-krepezh', 3, 0, 0),
(1, 'board', 'tsokolnaya-plitka', 1, 128, 1),
(2, 'board', 'tsokolnaya-plitka', 1, 254, 1),
(3, 'board', 'tsokolnaya-plitka', 0, 255, 1),
(4, 'board', 'tsokolnaya-plitka', 3, 0, 0),
(5, 'board', 'tsokolnaya-plitka', 255, 255, 1),
(6, 'board', 'tsokolnaya-plitka', 3, 0, 0),
(1, 'board', 'sypuchie-materialy', 1, 128, 1),
(2, 'board', 'sypuchie-materialy', 1, 254, 1),
(3, 'board', 'sypuchie-materialy', 0, 255, 1),
(4, 'board', 'sypuchie-materialy', 3, 0, 0),
(5, 'board', 'sypuchie-materialy', 255, 255, 1),
(6, 'board', 'sypuchie-materialy', 3, 0, 0),
(1, 'board', 'vermikulit', 1, 128, 1),
(2, 'board', 'vermikulit', 1, 254, 1),
(3, 'board', 'vermikulit', 0, 255, 1),
(4, 'board', 'vermikulit', 3, 0, 0),
(5, 'board', 'vermikulit', 255, 255, 1),
(6, 'board', 'vermikulit', 3, 0, 0),
(1, 'board', 'galka', 1, 128, 1),
(2, 'board', 'galka', 1, 254, 1),
(3, 'board', 'galka', 0, 255, 1),
(4, 'board', 'galka', 3, 0, 0),
(5, 'board', 'galka', 255, 255, 1),
(6, 'board', 'galka', 3, 0, 0),
(1, 'board', 'gips', 1, 128, 1),
(2, 'board', 'gips', 1, 254, 1),
(3, 'board', 'gips', 0, 255, 1),
(4, 'board', 'gips', 3, 0, 0),
(5, 'board', 'gips', 255, 255, 1),
(6, 'board', 'gips', 3, 0, 0),
(1, 'board', 'glina-i-grunt', 1, 128, 1),
(2, 'board', 'glina-i-grunt', 1, 254, 1),
(3, 'board', 'glina-i-grunt', 0, 255, 1),
(4, 'board', 'glina-i-grunt', 3, 0, 0),
(5, 'board', 'glina-i-grunt', 255, 255, 1),
(6, 'board', 'glina-i-grunt', 3, 0, 0),
(1, 'board', 'izvest', 1, 128, 1),
(2, 'board', 'izvest', 1, 254, 1),
(3, 'board', 'izvest', 0, 255, 1),
(4, 'board', 'izvest', 3, 0, 0),
(5, 'board', 'izvest', 255, 255, 1),
(6, 'board', 'izvest', 3, 0, 0),
(1, 'board', 'keramzit', 1, 128, 1),
(2, 'board', 'keramzit', 1, 254, 1),
(3, 'board', 'keramzit', 0, 255, 1),
(4, 'board', 'keramzit', 3, 0, 0),
(5, 'board', 'keramzit', 255, 255, 1),
(6, 'board', 'keramzit', 3, 0, 0),
(1, 'board', 'mramornaya-kroshka', 1, 128, 1),
(2, 'board', 'mramornaya-kroshka', 1, 254, 1),
(3, 'board', 'mramornaya-kroshka', 0, 255, 1),
(4, 'board', 'mramornaya-kroshka', 3, 0, 0),
(5, 'board', 'mramornaya-kroshka', 255, 255, 1),
(6, 'board', 'mramornaya-kroshka', 3, 0, 0),
(1, 'board', 'otsev', 1, 128, 1),
(2, 'board', 'otsev', 1, 254, 1),
(3, 'board', 'otsev', 0, 255, 1),
(4, 'board', 'otsev', 3, 0, 0),
(5, 'board', 'otsev', 255, 255, 1),
(6, 'board', 'otsev', 3, 0, 0),
(1, 'board', 'perlit', 1, 128, 1),
(2, 'board', 'perlit', 1, 254, 1),
(3, 'board', 'perlit', 0, 255, 1),
(4, 'board', 'perlit', 3, 0, 0),
(5, 'board', 'perlit', 255, 255, 1),
(6, 'board', 'perlit', 3, 0, 0),
(1, 'board', 'pesok', 1, 128, 1),
(2, 'board', 'pesok', 1, 254, 1),
(3, 'board', 'pesok', 0, 255, 1),
(4, 'board', 'pesok', 3, 0, 0),
(5, 'board', 'pesok', 255, 255, 1),
(6, 'board', 'pesok', 3, 0, 0),
(1, 'board', 'tsement', 1, 128, 1),
(2, 'board', 'tsement', 1, 254, 1),
(3, 'board', 'tsement', 0, 255, 1),
(4, 'board', 'tsement', 3, 0, 0),
(5, 'board', 'tsement', 255, 255, 1),
(6, 'board', 'tsement', 3, 0, 0),
(1, 'board', 'shlak', 1, 128, 1),
(2, 'board', 'shlak', 1, 254, 1),
(3, 'board', 'shlak', 0, 255, 1),
(4, 'board', 'shlak', 3, 0, 0),
(5, 'board', 'shlak', 255, 255, 1),
(6, 'board', 'shlak', 3, 0, 0),
(1, 'board', 'shcheben', 1, 128, 1),
(2, 'board', 'shcheben', 1, 254, 1),
(3, 'board', 'shcheben', 0, 255, 1),
(4, 'board', 'shcheben', 3, 0, 0),
(5, 'board', 'shcheben', 255, 255, 1),
(6, 'board', 'shcheben', 3, 0, 0),
(1, 'board', 'teplozvukoizolyatsiya', 1, 128, 1),
(2, 'board', 'teplozvukoizolyatsiya', 1, 254, 1),
(3, 'board', 'teplozvukoizolyatsiya', 0, 255, 1),
(4, 'board', 'teplozvukoizolyatsiya', 3, 0, 0),
(5, 'board', 'teplozvukoizolyatsiya', 255, 255, 1),
(6, 'board', 'teplozvukoizolyatsiya', 3, 0, 0),
(1, 'board', 'vysokotemperaturnaya-teploizolyatsiya', 1, 128, 1),
(2, 'board', 'vysokotemperaturnaya-teploizolyatsiya', 1, 254, 1),
(3, 'board', 'vysokotemperaturnaya-teploizolyatsiya', 0, 255, 1),
(4, 'board', 'vysokotemperaturnaya-teploizolyatsiya', 3, 0, 0),
(5, 'board', 'vysokotemperaturnaya-teploizolyatsiya', 255, 255, 1),
(6, 'board', 'vysokotemperaturnaya-teploizolyatsiya', 3, 0, 0),
(1, 'board', 'zvukoizolyatsiya', 1, 128, 1),
(2, 'board', 'zvukoizolyatsiya', 1, 254, 1),
(3, 'board', 'zvukoizolyatsiya', 0, 255, 1),
(4, 'board', 'zvukoizolyatsiya', 3, 0, 0),
(5, 'board', 'zvukoizolyatsiya', 255, 255, 1),
(6, 'board', 'zvukoizolyatsiya', 3, 0, 0),
(1, 'board', 'vysokotemperaturnaya-teploizolyatsiya', 1, 128, 1),
(2, 'board', 'vysokotemperaturnaya-teploizolyatsiya', 1, 254, 1),
(3, 'board', 'vysokotemperaturnaya-teploizolyatsiya', 0, 255, 1),
(4, 'board', 'vysokotemperaturnaya-teploizolyatsiya', 3, 0, 0),
(5, 'board', 'vysokotemperaturnaya-teploizolyatsiya', 255, 255, 1),
(6, 'board', 'vysokotemperaturnaya-teploizolyatsiya', 3, 0, 0),
(1, 'board', 'zvukoizolyatsiya', 1, 128, 1),
(2, 'board', 'zvukoizolyatsiya', 1, 254, 1),
(3, 'board', 'zvukoizolyatsiya', 0, 255, 1),
(4, 'board', 'zvukoizolyatsiya', 3, 0, 0),
(5, 'board', 'zvukoizolyatsiya', 255, 255, 1),
(6, 'board', 'zvukoizolyatsiya', 3, 0, 0),
(1, 'board', 'mineralnaya-vata', 1, 128, 1),
(2, 'board', 'mineralnaya-vata', 1, 254, 1),
(3, 'board', 'mineralnaya-vata', 0, 255, 1),
(4, 'board', 'mineralnaya-vata', 3, 0, 0),
(5, 'board', 'mineralnaya-vata', 255, 255, 1),
(6, 'board', 'mineralnaya-vata', 3, 0, 0),
(1, 'board', 'naturalnye-utepliteli', 1, 128, 1),
(2, 'board', 'naturalnye-utepliteli', 1, 254, 1),
(3, 'board', 'naturalnye-utepliteli', 0, 255, 1),
(4, 'board', 'naturalnye-utepliteli', 3, 0, 0),
(5, 'board', 'naturalnye-utepliteli', 255, 255, 1),
(6, 'board', 'naturalnye-utepliteli', 3, 0, 0),
(1, 'board', 'penoplast', 1, 128, 1),
(2, 'board', 'penoplast', 1, 254, 1),
(3, 'board', 'penoplast', 0, 255, 1),
(4, 'board', 'penoplast', 3, 0, 0),
(5, 'board', 'penoplast', 255, 255, 1),
(6, 'board', 'penoplast', 3, 0, 0),
(1, 'board', 'penosteklo', 1, 128, 1),
(2, 'board', 'penosteklo', 1, 254, 1),
(3, 'board', 'penosteklo', 0, 255, 1),
(4, 'board', 'penosteklo', 3, 0, 0),
(5, 'board', 'penosteklo', 255, 255, 1),
(6, 'board', 'penosteklo', 3, 0, 0),
(1, 'board', 'steklotkani', 1, 128, 1),
(2, 'board', 'steklotkani', 1, 254, 1),
(3, 'board', 'steklotkani', 0, 255, 1),
(4, 'board', 'steklotkani', 3, 0, 0),
(5, 'board', 'steklotkani', 255, 255, 1),
(6, 'board', 'steklotkani', 3, 0, 0),
(1, 'board', 'teploizolyatsionnye-smesi', 1, 128, 1),
(2, 'board', 'teploizolyatsionnye-smesi', 1, 254, 1),
(3, 'board', 'teploizolyatsionnye-smesi', 0, 255, 1),
(4, 'board', 'teploizolyatsionnye-smesi', 3, 0, 0),
(5, 'board', 'teploizolyatsionnye-smesi', 255, 255, 1),
(6, 'board', 'teploizolyatsionnye-smesi', 3, 0, 0),
(1, 'board', 'teploizolyatsiya-trub', 1, 128, 1),
(2, 'board', 'teploizolyatsiya-trub', 1, 254, 1),
(3, 'board', 'teploizolyatsiya-trub', 0, 255, 1),
(4, 'board', 'teploizolyatsiya-trub', 3, 0, 0),
(5, 'board', 'teploizolyatsiya-trub', 255, 255, 1),
(6, 'board', 'teploizolyatsiya-trub', 3, 0, 0),
(1, 'board', 'uplotniteli', 1, 128, 1),
(2, 'board', 'uplotniteli', 1, 254, 1),
(3, 'board', 'uplotniteli', 0, 255, 1),
(4, 'board', 'uplotniteli', 3, 0, 0),
(5, 'board', 'uplotniteli', 255, 255, 1),
(6, 'board', 'uplotniteli', 3, 0, 0),
(1, 'board', 'ekstrudirovannyy-penopolistirol', 1, 128, 1),
(2, 'board', 'ekstrudirovannyy-penopolistirol', 1, 254, 1),
(3, 'board', 'ekstrudirovannyy-penopolistirol', 0, 255, 1),
(4, 'board', 'ekstrudirovannyy-penopolistirol', 3, 0, 0),
(5, 'board', 'ekstrudirovannyy-penopolistirol', 255, 255, 1),
(6, 'board', 'ekstrudirovannyy-penopolistirol', 3, 0, 0),
(1, 'board', 'gidroizolyatsiya', 1, 128, 1),
(2, 'board', 'gidroizolyatsiya', 1, 254, 1),
(3, 'board', 'gidroizolyatsiya', 0, 255, 1),
(4, 'board', 'gidroizolyatsiya', 3, 0, 0),
(5, 'board', 'gidroizolyatsiya', 255, 255, 1),
(6, 'board', 'gidroizolyatsiya', 3, 0, 0),
(1, 'board', 'geosinteticheskie-materialy', 1, 128, 1),
(2, 'board', 'geosinteticheskie-materialy', 1, 254, 1),
(3, 'board', 'geosinteticheskie-materialy', 0, 255, 1),
(4, 'board', 'geosinteticheskie-materialy', 3, 0, 0),
(5, 'board', 'geosinteticheskie-materialy', 255, 255, 1),
(6, 'board', 'geosinteticheskie-materialy', 3, 0, 0),
(1, 'board', 'germetiki', 1, 128, 1),
(2, 'board', 'germetiki', 1, 254, 1),
(3, 'board', 'germetiki', 0, 255, 1),
(4, 'board', 'germetiki', 3, 0, 0),
(5, 'board', 'germetiki', 255, 255, 1),
(6, 'board', 'germetiki', 3, 0, 0),
(1, 'board', 'gidroizolyatsionnye-smesi', 1, 128, 1),
(2, 'board', 'gidroizolyatsionnye-smesi', 1, 254, 1),
(3, 'board', 'gidroizolyatsionnye-smesi', 0, 255, 1),
(4, 'board', 'gidroizolyatsionnye-smesi', 3, 0, 0),
(5, 'board', 'gidroizolyatsionnye-smesi', 255, 255, 1),
(6, 'board', 'gidroizolyatsionnye-smesi', 3, 0, 0),
(1, 'board', 'mastika-bitum', 1, 128, 1),
(2, 'board', 'mastika-bitum', 1, 254, 1),
(3, 'board', 'mastika-bitum', 0, 255, 1),
(4, 'board', 'mastika-bitum', 3, 0, 0),
(5, 'board', 'mastika-bitum', 255, 255, 1),
(6, 'board', 'mastika-bitum', 3, 0, 0),
(1, 'board', 'plenochnaya-gidroizolyatsiya', 1, 128, 1),
(2, 'board', 'plenochnaya-gidroizolyatsiya', 1, 254, 1),
(3, 'board', 'plenochnaya-gidroizolyatsiya', 0, 255, 1),
(4, 'board', 'plenochnaya-gidroizolyatsiya', 3, 0, 0),
(5, 'board', 'plenochnaya-gidroizolyatsiya', 255, 255, 1),
(6, 'board', 'plenochnaya-gidroizolyatsiya', 3, 0, 0),
(1, 'board', 'praymery', 1, 128, 1),
(2, 'board', 'praymery', 1, 254, 1),
(3, 'board', 'praymery', 0, 255, 1),
(4, 'board', 'praymery', 3, 0, 0),
(5, 'board', 'praymery', 255, 255, 1),
(6, 'board', 'praymery', 3, 0, 0),
(1, 'board', 'pronikayushchaya-gidroizolyatsiya', 1, 128, 1),
(2, 'board', 'pronikayushchaya-gidroizolyatsiya', 1, 254, 1),
(3, 'board', 'pronikayushchaya-gidroizolyatsiya', 0, 255, 1),
(4, 'board', 'pronikayushchaya-gidroizolyatsiya', 3, 0, 0),
(5, 'board', 'pronikayushchaya-gidroizolyatsiya', 255, 255, 1),
(6, 'board', 'pronikayushchaya-gidroizolyatsiya', 3, 0, 0),
(1, 'board', 'rulonnye-materialy', 1, 128, 1),
(2, 'board', 'rulonnye-materialy', 1, 254, 1),
(3, 'board', 'rulonnye-materialy', 0, 255, 1),
(4, 'board', 'rulonnye-materialy', 3, 0, 0),
(5, 'board', 'rulonnye-materialy', 255, 255, 1),
(6, 'board', 'rulonnye-materialy', 3, 0, 0),
(1, 'board', 'stroitelnaya-khimiya', 1, 128, 1),
(2, 'board', 'stroitelnaya-khimiya', 1, 254, 1),
(3, 'board', 'stroitelnaya-khimiya', 0, 255, 1),
(4, 'board', 'stroitelnaya-khimiya', 3, 0, 0),
(5, 'board', 'stroitelnaya-khimiya', 255, 255, 1),
(6, 'board', 'stroitelnaya-khimiya', 3, 0, 0),
(1, 'board', 'germetiki-pistoletnye', 1, 128, 1),
(2, 'board', 'germetiki-pistoletnye', 1, 254, 1),
(3, 'board', 'germetiki-pistoletnye', 0, 255, 1),
(4, 'board', 'germetiki-pistoletnye', 3, 0, 0),
(5, 'board', 'germetiki-pistoletnye', 255, 255, 1),
(6, 'board', 'germetiki-pistoletnye', 3, 0, 0),
(1, 'board', 'gruntovki', 1, 128, 1),
(2, 'board', 'gruntovki', 1, 254, 1),
(3, 'board', 'gruntovki', 0, 255, 1),
(4, 'board', 'gruntovki', 3, 0, 0),
(5, 'board', 'gruntovki', 255, 255, 1),
(6, 'board', 'gruntovki', 3, 0, 0),
(1, 'board', 'dekorativnye-shtukaturki', 1, 128, 1),
(2, 'board', 'dekorativnye-shtukaturki', 1, 254, 1),
(3, 'board', 'dekorativnye-shtukaturki', 0, 255, 1),
(4, 'board', 'dekorativnye-shtukaturki', 3, 0, 0),
(5, 'board', 'dekorativnye-shtukaturki', 255, 255, 1),
(6, 'board', 'dekorativnye-shtukaturki', 3, 0, 0),
(1, 'board', 'dobavki-dlya-stroitelnykh-smesey', 1, 128, 1),
(2, 'board', 'dobavki-dlya-stroitelnykh-smesey', 1, 254, 1),
(3, 'board', 'dobavki-dlya-stroitelnykh-smesey', 0, 255, 1),
(4, 'board', 'dobavki-dlya-stroitelnykh-smesey', 3, 0, 0),
(5, 'board', 'dobavki-dlya-stroitelnykh-smesey', 255, 255, 1),
(6, 'board', 'dobavki-dlya-stroitelnykh-smesey', 3, 0, 0),
(1, 'board', 'zatirka-dlya-shvov', 1, 128, 1),
(2, 'board', 'zatirka-dlya-shvov', 1, 254, 1),
(3, 'board', 'zatirka-dlya-shvov', 0, 255, 1),
(4, 'board', 'zatirka-dlya-shvov', 3, 0, 0),
(5, 'board', 'zatirka-dlya-shvov', 255, 255, 1),
(6, 'board', 'zatirka-dlya-shvov', 3, 0, 0),
(1, 'board', 'kladochnye-smesi', 1, 128, 1),
(2, 'board', 'kladochnye-smesi', 1, 254, 1),
(3, 'board', 'kladochnye-smesi', 0, 255, 1),
(4, 'board', 'kladochnye-smesi', 3, 0, 0),
(5, 'board', 'kladochnye-smesi', 255, 255, 1),
(6, 'board', 'kladochnye-smesi', 3, 0, 0),
(1, 'board', 'kleevye-smesi', 1, 128, 1),
(2, 'board', 'kleevye-smesi', 1, 254, 1),
(3, 'board', 'kleevye-smesi', 0, 255, 1),
(4, 'board', 'kleevye-smesi', 3, 0, 0),
(5, 'board', 'kleevye-smesi', 255, 255, 1),
(6, 'board', 'kleevye-smesi', 3, 0, 0),
(1, 'board', 'kley-kontaktnyy', 1, 128, 1),
(2, 'board', 'kley-kontaktnyy', 1, 254, 1),
(3, 'board', 'kley-kontaktnyy', 0, 255, 1),
(4, 'board', 'kley-kontaktnyy', 3, 0, 0),
(5, 'board', 'kley-kontaktnyy', 255, 255, 1),
(6, 'board', 'kley-kontaktnyy', 3, 0, 0),
(1, 'board', 'kley-pva', 1, 128, 1),
(2, 'board', 'kley-pva', 1, 254, 1),
(3, 'board', 'kley-pva', 0, 255, 1),
(4, 'board', 'kley-pva', 3, 0, 0),
(5, 'board', 'kley-pva', 255, 255, 1),
(6, 'board', 'kley-pva', 3, 0, 0),
(1, 'board', 'kley-stroitelnyy', 1, 128, 1),
(2, 'board', 'kley-stroitelnyy', 1, 254, 1),
(3, 'board', 'kley-stroitelnyy', 0, 255, 1),
(4, 'board', 'kley-stroitelnyy', 3, 0, 0),
(5, 'board', 'kley-stroitelnyy', 255, 255, 1),
(6, 'board', 'kley-stroitelnyy', 3, 0, 0),
(1, 'board', 'kley-epoksidnyy', 1, 128, 1),
(2, 'board', 'kley-epoksidnyy', 1, 254, 1),
(3, 'board', 'kley-epoksidnyy', 0, 255, 1),
(4, 'board', 'kley-epoksidnyy', 3, 0, 0),
(5, 'board', 'kley-epoksidnyy', 255, 255, 1),
(6, 'board', 'kley-epoksidnyy', 3, 0, 0),
(1, 'board', 'montazhnaya-pena', 1, 128, 1),
(2, 'board', 'montazhnaya-pena', 1, 254, 1),
(3, 'board', 'montazhnaya-pena', 0, 255, 1),
(4, 'board', 'montazhnaya-pena', 3, 0, 0),
(5, 'board', 'montazhnaya-pena', 255, 255, 1),
(6, 'board', 'montazhnaya-pena', 3, 0, 0),
(1, 'board', 'remontnye-smesi', 1, 128, 1),
(2, 'board', 'remontnye-smesi', 1, 254, 1),
(3, 'board', 'remontnye-smesi', 0, 255, 1),
(4, 'board', 'remontnye-smesi', 3, 0, 0),
(5, 'board', 'remontnye-smesi', 255, 255, 1),
(6, 'board', 'remontnye-smesi', 3, 0, 0),
(1, 'board', 'smesi-dlya-pola', 1, 128, 1),
(2, 'board', 'smesi-dlya-pola', 1, 254, 1),
(3, 'board', 'smesi-dlya-pola', 0, 255, 1),
(4, 'board', 'smesi-dlya-pola', 3, 0, 0),
(5, 'board', 'smesi-dlya-pola', 255, 255, 1),
(6, 'board', 'smesi-dlya-pola', 3, 0, 0),
(1, 'board', 'stroitelnyy-rastvor', 1, 128, 1),
(2, 'board', 'stroitelnyy-rastvor', 1, 254, 1),
(3, 'board', 'stroitelnyy-rastvor', 0, 255, 1),
(4, 'board', 'stroitelnyy-rastvor', 3, 0, 0),
(5, 'board', 'stroitelnyy-rastvor', 255, 255, 1),
(6, 'board', 'stroitelnyy-rastvor', 3, 0, 0),
(1, 'board', 'superkley', 1, 128, 1),
(2, 'board', 'superkley', 1, 254, 1),
(3, 'board', 'superkley', 0, 255, 1),
(4, 'board', 'superkley', 3, 0, 0),
(5, 'board', 'superkley', 255, 255, 1),
(6, 'board', 'superkley', 3, 0, 0),
(1, 'board', 'shpatlevka', 1, 128, 1),
(2, 'board', 'shpatlevka', 1, 254, 1),
(3, 'board', 'shpatlevka', 0, 255, 1),
(4, 'board', 'shpatlevka', 3, 0, 0),
(5, 'board', 'shpatlevka', 255, 255, 1),
(6, 'board', 'shpatlevka', 3, 0, 0),
(1, 'board', 'shtukaturka', 1, 128, 1),
(2, 'board', 'shtukaturka', 1, 254, 1),
(3, 'board', 'shtukaturka', 0, 255, 1),
(4, 'board', 'shtukaturka', 3, 0, 0),
(5, 'board', 'shtukaturka', 255, 255, 1),
(6, 'board', 'shtukaturka', 3, 0, 0);

-- Board table
CREATE TABLE IF NOT EXISTS `cot_board` (
  `adv_id` int(11) unsigned NOT NULL auto_increment,
  `adv_alias` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `adv_state` tinyint(1) unsigned NOT NULL default '0',
  `adv_cat` varchar(255) collate utf8_unicode_ci NOT NULL,
  `adv_title` varchar(255) collate utf8_unicode_ci NOT NULL,
  `adv_desc` MEDIUMTEXT collate utf8_unicode_ci default NULL,
  `adv_keywords` varchar(255) collate utf8_unicode_ci default NULL,
  `adv_metatitle` varchar(255) collate utf8_unicode_ci default NULL,
  `adv_metadesc` varchar(255) collate utf8_unicode_ci default NULL,
  `adv_text` TEXT collate utf8_unicode_ci NOT NULL,
  `adv_parser` VARCHAR(64) NOT NULL DEFAULT '',
  `adv_ownerid` int(11) NOT NULL default '0',
  `adv_date` int(11) NOT NULL default '0',
  `adv_updated` int(11) NOT NULL default '0',
  `adv_expire` int(11) NOT NULL default '0',
  `adv_count` mediumint(8) unsigned default '0',
  `adv_rating` decimal(5,2) NOT NULL default '0.00',
  `adv_cost` float(16,2) default NULL,
  `adv_addr` varchar(255) collate utf8_unicode_ci default NULL,
  `adv_phone` varchar(255) collate utf8_unicode_ci default NULL,
  `adv_skype` varchar(50) collate utf8_unicode_ci default NULL,
  `adv_site` varchar(255) collate utf8_unicode_ci default NULL,
  `adv_email` varchar(50) collate utf8_unicode_ci default NULL,
  `adv_hidemail` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`adv_id`),
  KEY `adv_cat` (`adv_cat`),
  KEY `adv_alias` (`adv_alias`),
  KEY `adv_state` (`adv_state`),
  KEY `adv_date` (`adv_date`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Default board categories

INSERT INTO `cot_structure` (`structure_area`, `structure_code`, `structure_path`, `structure_tpl`, `structure_title`, `structure_seotitle`,
   `structure_desc`, `structure_text`, `structure_metadesc`, `structure_icon`, `structure_locked`, `structure_count`) VALUES

('board', 'stroitelnye-materialy', '1', '', 'Металлопрокат и метизы', 'Металлопрокат и метизы','', '', '', '', 0, 0),
('board', 'alyuminievye-profili', '1.1', '', 'Алюминиевые профили', 'Алюминиевые профили','', '', '', '', 0, 0),
('board', 'armatura', '1.2', '', 'Арматура', 'Арматура','', '', '', '', 0, 0),
('board', 'balka-balka-metallicheskaya', '1.3', '', 'Балка, балка металлическая', 'Балка, балка металлическая','', '', '', '', 0, 0),
('board', 'kanaty-tsepi-tros', '1.4', '', 'Канаты, цепи, трос', 'Канаты, цепи, трос','', '', '', '', 0, 0),
('board', 'katanka-provoloka', '1.5', '', 'Катанка, проволока', 'Катанка, проволока','', '', '', '', 0, 0),
('board', 'kvadrat', '1.6', '', 'Квадрат', 'Квадрат','', '', '', '', 0, 0),
('board', 'krug', '1.7', '', 'Круг','Круг', '', '', '', '', 0, 0),
('board', 'list-listovoy-prokat', '1.8', '', 'Лист, листовой прокат','Лист, листовой прокат', '', '', '', '', 0, 0),
('board', 'polosa', '1.9', '', 'Полоса', 'Полоса','', '', '', '', 0, 0),
('board', 'profil-lstk', '1.10', '', 'Профиль ЛСТК', 'Профиль ЛСТК','', '', '', '', 0, 0),
('board', 'profilnye-truby', '1.11', '', 'Профильные трубы','Профильные трубы', '', '', '', '', 0, 0),
('board', 'setka-metallicheskaya', '1.12', '', 'Сетка металлическая','Сетка металлическая', '', '', '', '', 0, 0),
('board', 'ugolok', '1.13', '', 'Уголок', 'Уголок','', '', '', '', 0, 0),
('board', 'shveller', '1.14', '', 'Швеллер', 'Швеллер','', '', '', '', 0, 0),
('board', 'shestigrannik', '1.15', '', 'Шестигранник', 'Шестигранник','', '', '', '', 0, 0),
('board', 'shtrips-shtrips-otsinkovannyy', '1.16', '', 'Штрипс, штрипс оцинкованный','Штрипс, штрипс оцинкованный',  '', '', '', '', 0, 0),
('board', 'krovelnye-materialy', '2', '', 'Кровельные материалы', 'Кровельные материалы','', '', '', '', 0, 0),
('board', 'antiobledenenie', '2.1', '', 'Антиобледенение', 'Антиобледенение','', '', '', '', 0, 0),
('board', 'bitumnaya-cherepitsa', '2.2', '', 'Битумная черепица', 'Битумная черепица','', '', '', '', 0, 0),
('board', 'vodostochnye-sistemy', '2.3', '', 'Водосточные системы', 'Водосточные системы','', '', '', '', 0, 0),
('board', 'ventilyatsionnye-i-prokhodnye-elementy', '2.4', '', 'Вентиляционные и проходные элементы','Вентиляционные и проходные элементы', '', '', '', '', 0, 0),
('board', 'zenitnye-fonari-steklyannye-kryshi', '2.5', '', 'Зенитные фонари, стеклянные крыши', 'Зенитные фонари, стеклянные крыши','', '', '', '', 0, 0),
('board', 'keramoplast', '2.6', '', 'Керамопласт','Керамопласт', '', '', '', '', 0, 0),
('board', 'kompozitnaya-metallocherepitsa', '2.7', '', 'Композитная металлочерепица','Композитная металлочерепица', '', '', '', '', 0, 0),
('board', 'krovelnye-lenty', '2.8', '', 'Кровельные ленты','Кровельные ленты', '', '', '', '', 0, 0),
('board', 'krovelnyy-krepezh', '2.9', '', 'Кровельный крепеж', 'Кровельный крепеж','', '', '', '', 0, 0),
('board', 'metallocherepitsa', '2.10', '', 'Металлочерепица','Металлочерепица', '', '', '', '', 0, 0),
('board', 'podkrovelnye-plenki-i-membrany', '2.11', '', 'Подкровельные пленки и мембраны','Подкровельные пленки и мембраны', '', '', '', '', 0, 0),
('board', 'polikarbonat-orgsteklo', '2.12', '', 'Поликарбонат, оргстекло', 'Поликарбонат, оргстекло','', '', '', '', 0, 0),
('board', 'profnastil', '2.13', '', 'Профнастил', 'Профнастил','', '', '', '', 0, 0),
('board', 'sistemy-snegozaderzhaniya-lestnitsy', '2.14', '', 'Системы снегозадержания, лестницы','Системы снегозадержания, лестницы', '', '', '', '', 0, 0),
('board', 'faltsevaya-krovlya', '2.15', '', 'Фальцевая кровля','Фальцевая кровля', '', '', '', '', 0, 0),
('board', 'cherepitsa', '2.16', '', 'Черепица','Черепица', '', '', '', '', 0, 0),
('board', 'shifer-evroshifer', '2.17', '', 'Шифер, еврошифер', 'Шифер, еврошифер','', '', '', '', 0, 0),
('board', 'beton-zhbi', '3', '', 'Бетон, ЖБИ', 'Бетон, ЖБИ','', '', '', '', 0, 0),
('board', 'balki-progony-rigelya', '3.1', '', 'Балки, прогоны, ригеля', 'Балки, прогоны, ригеля', '', '', '', '', 0, 0),
('board', 'beton', '3.2', '', 'Бетон', 'Бетон','', '', '', '', 0, 0),
('board', 'ventilyatsionnye-bloki', '3.3', '', 'Вентиляционные блоки', 'Вентиляционные блоки','', '', '', '', 0, 0),
('board', 'dobavki-v-beton-plastifikatory-pigmenty', '3.4', '', 'Добавки в бетон, пластификаторы, пигменты', 'Добавки в бетон, пластификаторы, пигменты','', '', '', '', 0, 0),
('board', 'dorozhnye-plity', '3.5', '', 'Дорожные плиты', 'Дорожные плиты','', '', '', '', 0, 0),
('board', 'zhelezobetonnyy-zabor-evrozabor', '3.6', '', 'Железобетонный забор, еврозабор','Железобетонный забор, еврозабор', '', '', '', '', 0, 0),
('board', 'inzhenernye-seti', '3.7', '', 'Инженерные сети', 'Инженерные сети','', '', '', '', 0, 0),
('board', 'koltsa-kryshki-dno-dlya-kolodtsa', '3.8', '', 'Кольца, крышки, дно для колодца', 'Кольца, крышки, дно для колодца','', '', '', '', 0, 0),
('board', 'lestnichnye-marshi-i-stupeni', '3.9', '', 'Лестничные марши и ступени', 'Лестничные марши и ступени','', '', '', '', 0, 0),
('board', 'lestnichnye-ploshchadki', '3.10', '', 'Лестничные площадки', 'Лестничные площадки','', '', '', '', 0, 0),
('board', 'liftovye-shakhty', '3.11', '', 'Лифтовые шахты','Лифтовые шахты', '', '', '', '', 0, 0),
('board', 'lotki-plity-perekrytiya-lotkov', '3.12', '', 'Лотки, плиты перекрытия лотков', 'Лотки, плиты перекрытия лотков','', '', '', '', 0, 0),
('board', 'paneli-i-plity-perekrytiya', '3.13', '', 'Панели и плиты перекрытия', 'Панели и плиты перекрытия','', '', '', '', 0, 0),
('board', 'peremychki', '3.14', '', 'Перемычки', 'Перемычки','', '', '', '', 0, 0),
('board', 'plity-balkonov-i-lodzhiy', '3.15', '', 'Плиты балконов и лоджий', 'Плиты балконов и лоджий','', '', '', '', 0, 0),
('board', 'sbornye-zhelezobetonnye-garazhi', '3.16', '', 'Сборные железобетонные гаражи', 'Сборные железобетонные гаражи','', '', '', '', 0, 0),
('board', 'svai-opory-lep-stolby', '3.17', '', 'Сваи, опоры ЛЭП, столбы','Сваи, опоры ЛЭП, столбы', '', '', '', '', 0, 0),
('board', 'truby-zhelezobetonnye', '3.18', '', 'Трубы железобетонные', 'Трубы железобетонные','', '', '', '', 0, 0),
('board', 'fibra-fibrovolokno', '3.19', '', 'Фибра, фиброволокно',  'Фибра, фиброволокно','', '', '', '', 0, 0),
('board', 'fundamentnye-bloki-fundamenty', '3.20', '', 'Фундаментные блоки, фундаменты','Фундаментные блоки, фундаменты', '', '', '', '', 0, 0),
('board', 'pilomaterialy', '4', '', 'Пиломатериалы', 'Пиломатериалы','', '', '', '', 0, 0),
('board', 'bambuk-rattan-pressforming', '4.1', '', 'Бамбук, раттан, прессформинг', 'Бамбук, раттан, прессформинг','', '', '', '', 0, 0),
('board', 'blok-khaus', '4.2', '', 'Блок-хаус', 'Блок-хаус','', '', '', '', 0, 0),
('board', 'brus', '4.3', '', 'Брус', 'Брус','', '', '', '', 0, 0),
('board', 'brusok-i-reyka-montazhnaya', '4.4', '', 'Брусок и рейка монтажная','Брусок и рейка монтажная', '', '', '', '', 0, 0),
('board', 'dvp', '4.5', '', 'ДВП','ДВП', '', '', '', '', 0, 0),
('board', 'derevyannaya-vagonka', '4.6', '', 'Деревянная вагонкаy','Деревянная вагонкаy', '', '', '', '', 0, 0),
('board', 'doska-zabornaya', '4.7', '', 'Доска заборная', 'Доска заборная','', '', '', '', 0, 0),
('board', 'doska-neobreznaya-obapoly', '4.8', '', 'Доска необрезная, обаполы', 'Доска необрезная, обаполы','', '', '', '', 0, 0),
('board', 'doska-obreznaya', '4.9', '', 'Доска обрезная', 'Доска обрезная',  '', '', '', '', 0, 0),
('board', 'drova-kolotye-drova', '4.10', '', 'Дрова, колотые дрова', 'Дрова, колотые дрова','', '', '', '', 0, 0),
('board', 'dsp', '4.11', '', 'ДСП', 'ДСП', '', '', '', '', 0, 0),
('board', 'kleenyy-brus-i-profilirovannyy-brus', '4.12', '', 'Клееный брус и профилированный брус', 'Клееный брус и профилированный брус','', '', '', '', 0, 0),
('board', 'kruglye-lesomaterialy', '4.13', '', 'Круглые лесоматериалы','Круглые лесоматериалы', '', '', '', '', 0, 0),
('board', 'mdf', '4.14', '', 'МДФ','МДФ', '', '', '', '', 0, 0),
('board', 'mebelnye-shchity', '4.15', '', 'Мебельные щиты','Мебельные щиты', '', '', '', '', 0, 0),
('board', 'nalichniki', '4.16', '', 'Наличники', 'Наличники','', '', '', '', 0, 0),
('board', 'orientirovanno-struzhechnye-plity', '4.17', '', 'Ориентированно-стружечные плиты (OSB)','Ориентированно-стружечные плиты (OSB)', '', '', '', '', 0, 0),
('board', 'plintus', '4.18', '', 'Плинтус', 'Плинтус','', '', '', '', 0, 0),
('board', 'pogonazh', '4.19', '', 'Погонаж', 'Погонаж','', '', '', '', 0, 0),
('board', 'ugolok', '4.20', '', 'Уголок', 'Уголок','', '', '', '', 0, 0),
('board', 'falsh-brus', '4.21', '', 'Фальш-брус', 'Фальш-брус','', '', '', '', 0, 0),
('board', 'fanera', '4.22', '', 'Фанера', 'Фанера','', '', '', '', 0, 0),
('board', 'shpon-mebelnyy-shpon', '4.23', '', 'Шпон, мебельный шпон', 'Шпон, мебельный шпон', '', '', '', '', 0, 0),
('board', 'kladochnye-materialy', '5', '', 'Кладочные материалы', 'Кладочные материалы','', '', '', '', 0, 0),
('board', 'butovyy-kamen', '5.1', '', 'Бутовый камень','Бутовый камень', '', '', '', '', 0, 0),
('board', 'gazobloki-gazobeton', '5.2', '', 'Газоблоки, газобетон', 'Газоблоки, газобетон','', '', '', '', 0, 0),
('board', 'kamen-rakushnyak-rakushechnik', '5.3', '', 'Камень ракушняк, ракушечник', 'Камень ракушняк, ракушечник','', '', '', '', 0, 0),
('board', 'keramzitobetonnye-bloki', '5.4', '', 'Керамзитобетонные блоки', 'Керамзитобетонные блоки','', '', '', '', 0, 0),
('board', 'keramicheskie-bloki', '5.5', '', 'Керамические блоки', 'Керамические блоки','', '', '', '', 0, 0),
('board', 'kirpich-klinkernyy', '5.6', '', 'Кирпич клинкерный', 'Кирпич клинкерный','', '', '', '', 0, 0),
('board', 'kirpich-klinkernyy-ruchnoy-formovki', '5.7', '', 'Кирпич клинкерный ручной формовки', 'Кирпич клинкерный ручной формовки','', '', '', '', 0, 0),
('board', 'kirpich-ogneupornyy', '5.8', '', 'Кирпич огнеупорный','Кирпич огнеупорный', '', '', '', '', 0, 0),
('board', 'kirpich-ryadovoy', '5.9', '', 'Кирпич рядовой', 'Кирпич рядовой','', '', '', '', 0, 0),
('board', 'kirpich-silikatnyy', '5.10', '', 'Кирпич силикатный', 'Кирпич силикатный','', '', '', '', 0, 0),
('board', 'oblitsovochnyy-kirpich', '5.11', '', 'Облицовочный кирпич', 'Облицовочный кирпич','', '', '', '', 0, 0),
('board', 'parapet-kryshki-na-zabor', '5.12', '', 'Парапет, крышки на забор', 'Парапет, крышки на забор','', '', '', '', 0, 0),
('board', 'penobloki-penobeton', '5.13', '', 'Пеноблоки, пенобетон',  'Пеноблоки, пенобетон','', '', '', '', 0, 0),
('board', 'stenovye-bloki', '5.14', '', 'Стеновые блоки', 'Стеновые блоки','', '', '', '', 0, 0),
('board', 'termobloki', '5.15', '', 'Термоблоки', 'Термоблоки','', '', '', '', 0, 0),
('board', 'shlakobloki', '5.16', '', 'Шлакоблоки', 'Шлакоблоки','', '', '', '', 0, 0),
('board', 'fasadnye-materialy', '6', '', 'Фасадные материалы', 'Фасадные материалы','', '', '', '', 0, 0),
('board', 'ventiliruemye-fasady', '6.1', '', 'Вентилируемые фасады','Вентилируемые фасады', '', '', '', '', 0, 0),
('board', 'dekor-dlya-fasadov', '6.2', '', 'Декор для фасадов','Декор для фасадов', '', '', '', '', 0, 0),
('board', 'dyubelya-fasadnye', '6.3', '', 'Дюбеля фасадные', 'Дюбеля фасадные','', '', '', '', 0, 0),
('board', 'klinkernaya-plitka', '6.4', '', 'Клинкерная плитка', 'Клинкерная плитка', '', '', '', '', 0, 0),
('board', 'metallicheskie-paneli', '6.5', '', 'Металлические панели', 'Металлические панели','', '', '', '', 0, 0),
('board', 'oblitsovochnye-termopaneli', '6.6', '', 'Облицовочные термопанели', 'Облицовочные термопанели','', '', '', '', 0, 0),
('board', 'ochistka-fasadov', '6.7', '', 'Очистка фасадов', 'Очистка фасадов','', '', '', '', 0, 0),
('board', 'sayding', '6.8', '', 'Сайдинг', 'Сайдинг','', '', '', '', 0, 0),
('board', 'sistemy-utepleniya-fasadov', '6.9', '', 'Системы утепления фасадов', 'Системы утепления фасадов','', '', '', '', 0, 0),
('board', 'sofity', '6.10', '', 'Софиты', 'Софиты','', '', '', '', 0, 0),
('board', 'steklyannye-fasady', '6.11', '', 'Стеклянные фасады', 'Стеклянные фасады','', '', '', '', 0, 0),
('board', 'sendvich-paneli-sip-paneli', '6.12', '', 'Сэндвич панели, SIP-панели', 'Сэндвич панели, SIP-панели','', '', '', '', 0, 0),
('board', 'fasadnaya-plitka', '6.13', '', 'Фасадная плитка','Фасадная плитка', '', '', '', '', 0, 0),
('board', 'fasadnye-paneli', '6.14', '', 'Фасадные панели', 'Фасадные панели','', '', '', '', 0, 0),
('board', 'fasadnyy-kamen', '6.15', '', 'Фасадный камень',  'Фасадный камень','', '', '', '', 0, 0),
('board', 'fasadnyy-krepezh', '6.16', '', 'Фасадный крепеж', 'Фасадный крепеж','', '', '', '', 0, 0),
('board', 'tsokolnaya-plitka', '6.17', '', 'Цокольная плитка', 'Цокольная плитка','', '', '', '', 0, 0),
('board', 'sypuchie-materialy', '7', '', 'Сыпучие материалы', 'Сыпучие материалы','', '', '', '', 0, 0),
('board', 'vermikulit', '7.1', '', 'Вермикулит', 'Вермикулит','', '', '', '', 0, 0),
('board', 'galka', '7.2', '', 'Галька', 'Галька','', '', '', '', 0, 0),
('board', 'gips', '7.3', '',  'Гипс', 'Гипс','', '', '', '', 0, 0),
('board', 'glina-i-grunt', '7.4', '', 'Глина и грунт', 'Глина и грунт','', '', '', '', 0, 0),
('board', 'izvest', '7.5', '', 'Известь','Известь', '', '', '', '', 0, 0),
('board', 'keramzit', '7.6', '', 'Керамзит', 'Керамзит','', '', '', '', 0, 0),
('board', 'mramornaya-kroshka', '7.7', '', 'Мраморная крошка','Мраморная крошка', '', '', '', '', 0, 0),
('board', 'otsev', '7.8', '', 'Отсев', 'Отсев','', '', '', '', 0, 0),
('board', 'perlit', '7.9', '', 'Перлит', 'Перлит','', '', '', '', 0, 0),
('board', 'pesok', '7.10', '', 'Песок', 'Песок','', '', '', '', 0, 0),
('board', 'tsement', '7.11', '', 'Цемент', 'Цемент','', '', '', '', 0, 0),
('board', 'shlak', '7.12', '', 'Шлак', 'Шлак','', '', '', '', 0, 0),
('board', 'shcheben', '7.13', '', 'Щебень',  'Щебень','', '', '', '', 0, 0),
('board', 'teplozvukoizolyatsiya', '8', '', 'Теплозвукоизоляция','Теплозвукоизоляция', '', '', '', '', 0, 0),
('board', 'vysokotemperaturnaya-teploizolyatsiya', '8.1', '', 'Высокотемпературная теплоизоляция', 'Высокотемпературная теплоизоляция','', '', '', '', 0, 0),
('board', 'zvukoizolyatsiya', '8.2', '', 'Звукоизоляция', 'Звукоизоляция','', '', '', '', 0, 0),
('board', 'mineralnaya-vata', '8.3', '', 'Минеральная вата',  'Минеральная вата','', '', '', '', 0, 0),
('board', 'naturalnye-utepliteli', '8.4', '', 'Натуральные утеплители', 'Натуральные утеплители','', '', '', '', 0, 0),
('board', 'penoplast', '8.5', '', 'Пенопласт', 'Пенопласт','', '', '', '', 0, 0),
('board', 'penosteklo', '8.6', '', 'Пеностекло', 'Пеностекло','', '', '', '', 0, 0),
('board', 'steklotkani', '8.7', '', 'Стеклоткани', 'Стеклоткани','', '', '', '', 0, 0),
('board', 'teploizolyatsionnye-smesi', '8.8', '', 'Теплоизоляционные смеси','Теплоизоляционные смеси', '', '', '', '', 0, 0),
('board', 'teploizolyatsiya-trub', '8.9', '', 'Теплоизоляция труб', 'Теплоизоляция труб','', '', '', '', 0, 0),
('board', 'uplotniteli', '8.10', '', 'Уплотнители','Уплотнители', '', '', '', '', 0, 0),
('board', 'ekstrudirovannyy-penopolistirol', '8.11', '', 'Экструдированный пенополистирол', 'Экструдированный пенополистирол','', '', '', '', 0, 0),
('board', 'gidroizolyatsiya', '9', '', 'Гидроизоляция', 'Гидроизоляция','', '', '', '', 0, 0),
('board', 'geosinteticheskie-materialy', '9.1', '', 'Геосинтетические материалы','Геосинтетические материалы', '', '', '', '', 0, 0),
('board', 'germetiki', '9.2', '', 'Герметики', 'Герметики','', '', '', '', 0, 0),
('board', 'gidroizolyatsionnye-smesi', '9.3', '', 'Гидроизоляционные смеси','Гидроизоляционные смеси', '', '', '', '', 0, 0),
('board', 'mastika-bitum', '9.4', '', 'Мастика, битум', 'Мастика, битум', '', '', '', '', 0, 0),
('board', 'plenochnaya-gidroizolyatsiya', '9.5', '', 'Пленочная гидроизоляция', 'Пленочная гидроизоляция','', '', '', '', 0, 0),
('board', 'praymery', '9.6', '', 'Праймеры', 'Праймеры', '', '', '', '', 0, 0),
('board', 'pronikayushchaya-gidroizolyatsiya', '9.7', '', 'Проникающая гидроизоляция', 'Проникающая гидроизоляция','', '', '', '', 0, 0),
('board', 'rulonnye-materialy', '9.8', '', 'Рулонные материалы', 'Рулонные материалы','', '', '', '', 0, 0),
('board', 'stroitelnaya-khimiya', '10', '', 'Строительная химия', 'Строительная химия','', '', '', '', 0, 0),
('board', 'germetiki-pistoletnye', '10.1', '', 'Герметики пистолетные', 'Герметики пистолетные','', '', '', '', 0, 0),
('board', 'gruntovki', '10.2', '', 'Грунтовки', 'Грунтовки','', '', '', '', 0, 0),
('board', 'dekorativnye-shtukaturki', '10.3', '', 'Декоративные штукатурки', 'Декоративные штукатурки','', '', '', '', 0, 0),
('board', 'dobavki-dlya-stroitelnykh-smesey', '10.4', '', 'Добавки для строительных смесей','Добавки для строительных смесей', '', '', '', '', 0, 0),
('board', 'zatirka-dlya-shvov', '10.5', '', 'Затирка для швов','Затирка для швов', '', '', '', '', 0, 0),
('board', 'kladochnye-smesi', '10.6', '', 'Кладочные смеси', 'Кладочные смеси','', '', '', '', 0, 0),
('board', 'kleevye-smesi', '10.7', '', 'Клеевые смеси', 'Клеевые смеси','', '', '', '', 0, 0),
('board', 'kley-kontaktnyy', '10.8', '', 'Клей контактный', 'Клей контактный','', '', '', '', 0, 0),
('board', 'kley-pva', '10.9', '', 'Клей ПВА', 'Клей ПВА','', '', '', '', 0, 0),
('board', 'kley-stroitelnyy', '10.10', '', 'Клей строительный', 'Клей строительный','', '', '', '', 0, 0),
('board', 'kley-epoksidnyy', '10.11', '', 'Клей эпоксидный', 'Клей эпоксидный','', '', '', '', 0, 0),
('board', 'montazhnaya-pena', '10.12', '', 'Монтажная пена', 'Монтажная пена','', '', '', '', 0, 0),
('board', 'remontnye-smesi', '10.13', '', 'Ремонтные смеси',  'Ремонтные смеси','', '', '', '', 0, 0),
('board', 'smesi-dlya-pola', '10.14', 'Смеси для пола',  'Смеси для пола', '', '', '', '', '', 0, 0),
('board', 'stroitelnyy-rastvor', '10.15', '', 'Строительный раствор', 'Строительный раствор','', '', '', '', 0, 0),
('board', 'superkley', '10.16', '', 'Суперклей', 'Суперклей','', '', '', '', 0, 0),
('board', 'shpatlevka', '10.17', '', 'Шпатлевка', 'Шпатлевка','', '', '', '', 0, 0),
('board', 'shtukaturka', '10.18', '', 'Штукатурка', 'Штукатурка','', '', '', '', 0, 0);