<!-- BEGIN: FOOTER -->
	</div>
</div>
<div id="footer" class="container">
	<div class="floatright">
		Generated by <a href="http://cotonti.com" target="blank">CMF Cotonti</a><br/>
		Powered by <a href="http://cmsworks.ru" target="blank">CMSWorks.ru</a>
	</div>
	&copy; 2013 {PHP.cfg.maintitle}
</div>

<!-- BEGIN JIVOSITE CODE {literal} -->
<script type='text/javascript2'>
(function(){ var widget_id = 'rEGi4wjLCv';



var s = document.createElement('script');
  s.type = 'text/javascript'; s.async = true; 
  s.src = '//code.jivosite.com/script/widget/'+widget_id;
  var ss = document.getElementsByTagName('script')[0]; 
  ss.parentNode.insertBefore(s, ss);



})();


function changeFucntion(label, placeholder) {
  
  $('#jivo-label-text').text(label);
  $(".new-msg-text-inner").text('123');



 
}

setTimeout(changeFucntion, 1500, "Меняю лейбел", "Вася"); // Привет, Вася



</script>
<!-- {/literal} END JIVOSITE CODE -->

{FOOTER_RC}
</body>
</html>
<!-- END: FOOTER -->