/**
 * Page module DB installation
 */

-- Default categories permssions
INSERT INTO `cot_auth` (`auth_groupid`, `auth_code`, `auth_option`,
  `auth_rights`, `auth_rights_lock`, `auth_setbyuserid`) VALUES
(1, 'page', 'news', 5, 250, 1),
(2, 'page', 'news', 1, 254, 1),
(3, 'page', 'news', 0, 255, 1),
(4, 'page', 'news', 7, 0, 1),
(5, 'page', 'news', 255, 255, 1),
(6, 'page', 'news', 135, 0, 1),
(1, 'page', 'politics', 5, 250, 1),
(2, 'page', 'politics', 1, 254, 1),
(3, 'page', 'politics', 0, 255, 1),
(4, 'page', 'politics', 7, 0, 1),
(5, 'page', 'politics', 255, 255, 1),
(6, 'page', 'politics', 135, 0, 1),
(1, 'page', 'society', 5, 250, 1),
(2, 'page', 'society', 1, 254, 1),
(3, 'page', 'society', 0, 255, 1),
(4, 'page', 'society', 7, 0, 1),
(5, 'page', 'society', 255, 255, 1),
(6, 'page', 'society', 135, 0, 1),
(1, 'page', 'economics', 5, 250, 1),
(2, 'page', 'economics', 1, 254, 1),
(3, 'page', 'economics', 0, 255, 1),
(4, 'page', 'economics', 7, 0, 1),
(5, 'page', 'economics', 255, 255, 1),
(6, 'page', 'economics', 135, 0, 1),
(5, 'page', 'incidents', 255, 255, 1),
(6, 'page', 'incidents', 3, 0, 1),
(2, 'page', 'incidents', 1, 254, 1),
(3, 'page', 'incidents', 0, 255, 1),
(4, 'page', 'incidents', 3, 0, 1),
(1, 'page', 'incidents', 1, 128, 1),
(5, 'page', 'culture', 255, 255, 1),
(6, 'page', 'culture', 3, 0, 1),
(2, 'page', 'culture', 1, 254, 1),
(3, 'page', 'culture', 0, 255, 1),
(4, 'page', 'culture', 3, 0, 1),
(1, 'page', 'culture', 1, 128, 1),
(5, 'page', 'sport', 255, 255, 1),
(6, 'page', 'sport', 3, 0, 1),
(2, 'page', 'sport', 1, 254, 1),
(3, 'page', 'sport', 0, 255, 1),
(4, 'page', 'sport', 3, 0, 1),
(1, 'page', 'sport', 1, 128, 1),
(5, 'page', 'company', 255, 255, 1),
(6, 'page', 'company', 3, 0, 1),
(2, 'page', 'company', 1, 254, 1),
(3, 'page', 'company', 0, 255, 1),
(4, 'page', 'company', 3, 0, 1),
(1, 'page', 'company', 1, 128, 1),
(5, 'page', 'about', 255, 255, 1),
(6, 'page', 'about', 3, 0, 1),
(2, 'page', 'about', 1, 254, 1),
(3, 'page', 'about', 0, 255, 1),
(4, 'page', 'about', 3, 0, 1),
(1, 'page', 'about', 1, 128, 1),
(5, 'page', 'advertising', 255, 255, 1),
(6, 'page', 'advertising', 3, 0, 1),
(2, 'page', 'advertising', 1, 254, 1),
(3, 'page', 'advertising', 0, 255, 1),
(4, 'page', 'advertising', 3, 0, 1),
(1, 'page', 'advertising', 1, 128, 1),
(5, 'page', 'team', 255, 255, 1),
(6, 'page', 'team', 3, 0, 1),
(2, 'page', 'team', 1, 254, 1),
(3, 'page', 'team', 0, 255, 1),
(4, 'page', 'team', 3, 0, 1),
(1, 'page', 'team', 1, 128, 1),
(5, 'page', 'agreement', 255, 255, 1),
(6, 'page', 'agreement', 3, 0, 1),
(2, 'page', 'agreement', 1, 254, 1),
(3, 'page', 'agreement', 0, 255, 1),
(4, 'page', 'agreement', 3, 0, 1),
(1, 'page', 'agreement', 1, 128, 1),
(1, 'page', 'system', 1, 128, 1),
(2, 'page', 'system', 1, 254, 1),
(3, 'page', 'system', 0, 255, 1),
(4, 'page', 'system', 3, 0, 1),
(5, 'page', 'system', 255, 255, 1),
(6, 'page', 'system', 3, 0, 1);

CREATE TABLE IF NOT EXISTS `cot_pages` (
  `page_id` int(11) unsigned NOT NULL auto_increment,
  `page_alias` varchar(255) collate utf8_unicode_ci NOT NULL default '',
  `page_state` tinyint(1) unsigned NOT NULL default '0',
  `page_cat` varchar(255) collate utf8_unicode_ci NOT NULL,
  `page_title` varchar(255) collate utf8_unicode_ci NOT NULL,
  `page_desc` MEDIUMTEXT collate utf8_unicode_ci default NULL,
  `page_keywords` varchar(255) collate utf8_unicode_ci default NULL,
  `page_metatitle` varchar(255) collate utf8_unicode_ci default NULL,
  `page_metadesc` varchar(255) collate utf8_unicode_ci default NULL,
  `page_text` TEXT collate utf8_unicode_ci NOT NULL,
  `page_parser` VARCHAR(64) NOT NULL DEFAULT '',
  `page_author` varchar(100) collate utf8_unicode_ci NOT NULL,
  `page_city` varchar(100) collate utf8_unicode_ci NOT NULL,
  `page_ownerid` int(11) NOT NULL default '0',
  `page_date` int(11) NOT NULL default '0',
  `page_begin` int(11) NOT NULL default '0',
  `page_expire` int(11) NOT NULL default '0',
  `page_updated` int(11) NOT NULL default '0',
  `page_file` tinyint(4) default NULL,
  `page_url` varchar(255) collate utf8_unicode_ci default NULL,
  `page_size` int(11) unsigned default NULL,
  `page_count` mediumint(8) unsigned default '0',
  `page_rating` decimal(5,2) NOT NULL default '0.00',
  `page_filecount` mediumint(8) unsigned default '0',
  `page_tpl` varchar(120) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY  (`page_id`),
  KEY `page_cat` (`page_cat`),
  KEY `page_alias` (`page_alias`),
  KEY `page_date` (`page_date`),
  KEY `page_ownerid` (`page_ownerid`),
  KEY `page_begin` (`page_begin`),
  KEY `page_expire` (`page_expire`),
  KEY `page_title` (`page_title`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `cot_pages` (`page_state`, `page_cat`, `page_title`, `page_desc`, `page_text`, `page_author`, `page_ownerid`, `page_date`, `page_begin`, `page_expire`, `page_file`, `page_url`, `page_size`, `page_count`, `page_rating`, `page_filecount`, `page_alias`) VALUES
(0, 'news', 'Welcome!', '', 'Congratulations, Cotonti was successfully installed! You can now login with the user account you created during installation. Next step is to go to the Administration panel and change the settings for your website, such as the title, server settings, language, user groups and extensions. You can safely remove this message by clicking its title, then clicking Edit and Delete this page.', '', 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), 0, 0, '', 0, 27, '0.00', 0, '');

-- Default page categories
INSERT INTO `cot_structure` (`structure_area`, `structure_code`, `structure_path`, `structure_tpl`, `structure_title`, `structure_seotitle`,
   `structure_desc`, `structure_text`, `structure_icon`, `structure_locked`, `structure_count`) VALUES
('page', 'news', '1', '', 'Новости', 'Новости', '', '', '', 0, 1),
('page', 'society', '1.3', '', 'Общество', 'Общество', '', '', '', 0, 0),
('page', 'politics', '1.1', '', 'Политика', 'Политика', '', '', '', 0, 0),
('page', 'economics', '1.2', '', 'Экономика', 'Экономика', '', '', '', 0, 0),
('page', 'incidents', '1.4', '', 'Происшествия', 'Происшествия', '', '', '', 0, 0),
('page', 'culture', '1.5', '', 'Культура', 'Культура', '', '', '', 0, 0),
('page', 'sport', '1.6', '', 'Спорт', 'Спорт', '', '', '', 0, 0),
('page', 'company', '1.7', '', 'Новости компаний', 'Новости компаний', '', '', '', 0, 0),
('page', 'about', '2', '', 'О портале', 'О портале', '', '', '', 0, 0),
('page', 'advertising', '2.1', '', 'Реклама на портале', 'Реклама на портале', '', '', '', 0, 0),
('page', 'team', '2.2', '', 'Наша команда', 'Наша команда', '', '', '', 0, 0),
('page', 'agreement', '2.3', '', 'Пользовательское соглашение', 'Пользовательское соглашение', '', '', '', 0, 0),
('page', 'system', '999', '', 'System', 'System', '', '', '', 0, 0);

-- Pages_in_structure table
CREATE TABLE IF NOT EXISTS `cot_pages_in_structure` (
  `page_id` int(11) NOT NULL,
  `structure_code` varchar(255) collate utf8_unicode_ci NOT NULL default ''
)ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `cot_pages_in_structure` (`page_id`, `structure_code`) VALUES
(1, 'news');